/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Chapter error response schema.
 */
export type ChapterErrorResponseData = {
  message: string;
};

/**
 * Chapter error response schema.
 */
export class ChapterErrorResponse extends NestError {
  /** The original data that was passed to this error instance. */
  data$: ChapterErrorResponseData;

  constructor(
    err: ChapterErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ChapterErrorResponse";
  }
}

/** @internal */
export const ChapterErrorResponse$inboundSchema: z.ZodType<
  ChapterErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ChapterErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ChapterErrorResponse$Outbound = {
  message: string;
};

/** @internal */
export const ChapterErrorResponse$outboundSchema: z.ZodType<
  ChapterErrorResponse$Outbound,
  z.ZodTypeDef,
  ChapterErrorResponse
> = z.instanceof(ChapterErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChapterErrorResponse$ {
  /** @deprecated use `ChapterErrorResponse$inboundSchema` instead. */
  export const inboundSchema = ChapterErrorResponse$inboundSchema;
  /** @deprecated use `ChapterErrorResponse$outboundSchema` instead. */
  export const outboundSchema = ChapterErrorResponse$outboundSchema;
  /** @deprecated use `ChapterErrorResponse$Outbound` instead. */
  export type Outbound = ChapterErrorResponse$Outbound;
}
