/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Chapter error schema.
 */
export type ChapterErrorData = {
  message: string;
};

/**
 * Chapter error schema.
 */
export class ChapterError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: ChapterErrorData;

  constructor(
    err: ChapterErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ChapterError";
  }
}

/** @internal */
export const ChapterError$inboundSchema: z.ZodType<
  ChapterError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ChapterError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ChapterError$Outbound = {
  message: string;
};

/** @internal */
export const ChapterError$outboundSchema: z.ZodType<
  ChapterError$Outbound,
  z.ZodTypeDef,
  ChapterError
> = z.instanceof(ChapterError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChapterError$ {
  /** @deprecated use `ChapterError$inboundSchema` instead. */
  export const inboundSchema = ChapterError$inboundSchema;
  /** @deprecated use `ChapterError$outboundSchema` instead. */
  export const outboundSchema = ChapterError$outboundSchema;
  /** @deprecated use `ChapterError$Outbound` instead. */
  export type Outbound = ChapterError$Outbound;
}
