/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Chapter error schema.
 */
export type ChapterErrorData = {
  message: string;
};

/**
 * Chapter error schema.
 */
export class ChapterError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: ChapterErrorData;

  constructor(
    err: ChapterErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ChapterError";
  }
}

/** @internal */
export const ChapterError$inboundSchema: z.ZodType<
  ChapterError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ChapterError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
