/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Committee error schema.
 */
export type CommitteeErrorData = {
  message: string;
};

/**
 * Committee error schema.
 */
export class CommitteeError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: CommitteeErrorData;

  constructor(
    err: CommitteeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "CommitteeError";
  }
}

/** @internal */
export const CommitteeError$inboundSchema: z.ZodType<
  CommitteeError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CommitteeError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
