/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Committee error schema.
 */
export type CommitteeErrorData = {
  message: string;
};

/**
 * Committee error schema.
 */
export class CommitteeError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: CommitteeErrorData;

  constructor(
    err: CommitteeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "CommitteeError";
  }
}

/** @internal */
export const CommitteeError$inboundSchema: z.ZodType<
  CommitteeError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CommitteeError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CommitteeError$Outbound = {
  message: string;
};

/** @internal */
export const CommitteeError$outboundSchema: z.ZodType<
  CommitteeError$Outbound,
  z.ZodTypeDef,
  CommitteeError
> = z.instanceof(CommitteeError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommitteeError$ {
  /** @deprecated use `CommitteeError$inboundSchema` instead. */
  export const inboundSchema = CommitteeError$inboundSchema;
  /** @deprecated use `CommitteeError$outboundSchema` instead. */
  export const outboundSchema = CommitteeError$outboundSchema;
  /** @deprecated use `CommitteeError$Outbound` instead. */
  export type Outbound = CommitteeError$Outbound;
}
