/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Committee error response schema.
 */
export type CommitteeErrorResponseData = {
  message: string;
};

/**
 * Committee error response schema.
 */
export class CommitteeErrorResponse extends NestError {
  /** The original data that was passed to this error instance. */
  data$: CommitteeErrorResponseData;

  constructor(
    err: CommitteeErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "CommitteeErrorResponse";
  }
}

/** @internal */
export const CommitteeErrorResponse$inboundSchema: z.ZodType<
  CommitteeErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CommitteeErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CommitteeErrorResponse$Outbound = {
  message: string;
};

/** @internal */
export const CommitteeErrorResponse$outboundSchema: z.ZodType<
  CommitteeErrorResponse$Outbound,
  z.ZodTypeDef,
  CommitteeErrorResponse
> = z.instanceof(CommitteeErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommitteeErrorResponse$ {
  /** @deprecated use `CommitteeErrorResponse$inboundSchema` instead. */
  export const inboundSchema = CommitteeErrorResponse$inboundSchema;
  /** @deprecated use `CommitteeErrorResponse$outboundSchema` instead. */
  export const outboundSchema = CommitteeErrorResponse$outboundSchema;
  /** @deprecated use `CommitteeErrorResponse$Outbound` instead. */
  export type Outbound = CommitteeErrorResponse$Outbound;
}
