/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Event error schema.
 */
export type EventErrorData = {
  message: string;
};

/**
 * Event error schema.
 */
export class EventError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: EventErrorData;

  constructor(
    err: EventErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "EventError";
  }
}

/** @internal */
export const EventError$inboundSchema: z.ZodType<
  EventError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new EventError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type EventError$Outbound = {
  message: string;
};

/** @internal */
export const EventError$outboundSchema: z.ZodType<
  EventError$Outbound,
  z.ZodTypeDef,
  EventError
> = z.instanceof(EventError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EventError$ {
  /** @deprecated use `EventError$inboundSchema` instead. */
  export const inboundSchema = EventError$inboundSchema;
  /** @deprecated use `EventError$outboundSchema` instead. */
  export const outboundSchema = EventError$outboundSchema;
  /** @deprecated use `EventError$Outbound` instead. */
  export type Outbound = EventError$Outbound;
}
