/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Member error schema.
 */
export type MemberErrorData = {
  message: string;
};

/**
 * Member error schema.
 */
export class MemberError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: MemberErrorData;

  constructor(
    err: MemberErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "MemberError";
  }
}

/** @internal */
export const MemberError$inboundSchema: z.ZodType<
  MemberError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new MemberError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type MemberError$Outbound = {
  message: string;
};

/** @internal */
export const MemberError$outboundSchema: z.ZodType<
  MemberError$Outbound,
  z.ZodTypeDef,
  MemberError
> = z.instanceof(MemberError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MemberError$ {
  /** @deprecated use `MemberError$inboundSchema` instead. */
  export const inboundSchema = MemberError$inboundSchema;
  /** @deprecated use `MemberError$outboundSchema` instead. */
  export const outboundSchema = MemberError$outboundSchema;
  /** @deprecated use `MemberError$Outbound` instead. */
  export type Outbound = MemberError$Outbound;
}
