/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Milestone error schema.
 */
export type MilestoneErrorData = {
  message: string;
};

/**
 * Milestone error schema.
 */
export class MilestoneError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: MilestoneErrorData;

  constructor(
    err: MilestoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "MilestoneError";
  }
}

/** @internal */
export const MilestoneError$inboundSchema: z.ZodType<
  MilestoneError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new MilestoneError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type MilestoneError$Outbound = {
  message: string;
};

/** @internal */
export const MilestoneError$outboundSchema: z.ZodType<
  MilestoneError$Outbound,
  z.ZodTypeDef,
  MilestoneError
> = z.instanceof(MilestoneError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MilestoneError$ {
  /** @deprecated use `MilestoneError$inboundSchema` instead. */
  export const inboundSchema = MilestoneError$inboundSchema;
  /** @deprecated use `MilestoneError$outboundSchema` instead. */
  export const outboundSchema = MilestoneError$outboundSchema;
  /** @deprecated use `MilestoneError$Outbound` instead. */
  export type Outbound = MilestoneError$Outbound;
}
