/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Organization error response schema.
 */
export type OrganizationErrorResponseData = {
  message: string;
};

/**
 * Organization error response schema.
 */
export class OrganizationErrorResponse extends NestError {
  /** The original data that was passed to this error instance. */
  data$: OrganizationErrorResponseData;

  constructor(
    err: OrganizationErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "OrganizationErrorResponse";
  }
}

/** @internal */
export const OrganizationErrorResponse$inboundSchema: z.ZodType<
  OrganizationErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new OrganizationErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type OrganizationErrorResponse$Outbound = {
  message: string;
};

/** @internal */
export const OrganizationErrorResponse$outboundSchema: z.ZodType<
  OrganizationErrorResponse$Outbound,
  z.ZodTypeDef,
  OrganizationErrorResponse
> = z.instanceof(OrganizationErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationErrorResponse$ {
  /** @deprecated use `OrganizationErrorResponse$inboundSchema` instead. */
  export const inboundSchema = OrganizationErrorResponse$inboundSchema;
  /** @deprecated use `OrganizationErrorResponse$outboundSchema` instead. */
  export const outboundSchema = OrganizationErrorResponse$outboundSchema;
  /** @deprecated use `OrganizationErrorResponse$Outbound` instead. */
  export type Outbound = OrganizationErrorResponse$Outbound;
}
