/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Organization error schema.
 */
export type OrganizationErrorData = {
  message: string;
};

/**
 * Organization error schema.
 */
export class OrganizationError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: OrganizationErrorData;

  constructor(
    err: OrganizationErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "OrganizationError";
  }
}

/** @internal */
export const OrganizationError$inboundSchema: z.ZodType<
  OrganizationError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new OrganizationError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type OrganizationError$Outbound = {
  message: string;
};

/** @internal */
export const OrganizationError$outboundSchema: z.ZodType<
  OrganizationError$Outbound,
  z.ZodTypeDef,
  OrganizationError
> = z.instanceof(OrganizationError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationError$ {
  /** @deprecated use `OrganizationError$inboundSchema` instead. */
  export const inboundSchema = OrganizationError$inboundSchema;
  /** @deprecated use `OrganizationError$outboundSchema` instead. */
  export const outboundSchema = OrganizationError$outboundSchema;
  /** @deprecated use `OrganizationError$Outbound` instead. */
  export type Outbound = OrganizationError$Outbound;
}
