/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Project error schema.
 */
export type ProjectErrorData = {
  message: string;
};

/**
 * Project error schema.
 */
export class ProjectError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: ProjectErrorData;

  constructor(
    err: ProjectErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ProjectError";
  }
}

/** @internal */
export const ProjectError$inboundSchema: z.ZodType<
  ProjectError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ProjectError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ProjectError$Outbound = {
  message: string;
};

/** @internal */
export const ProjectError$outboundSchema: z.ZodType<
  ProjectError$Outbound,
  z.ZodTypeDef,
  ProjectError
> = z.instanceof(ProjectError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectError$ {
  /** @deprecated use `ProjectError$inboundSchema` instead. */
  export const inboundSchema = ProjectError$inboundSchema;
  /** @deprecated use `ProjectError$outboundSchema` instead. */
  export const outboundSchema = ProjectError$outboundSchema;
  /** @deprecated use `ProjectError$Outbound` instead. */
  export type Outbound = ProjectError$Outbound;
}
