/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Project error response schema.
 */
export type ProjectErrorResponseData = {
  message: string;
};

/**
 * Project error response schema.
 */
export class ProjectErrorResponse extends NestError {
  /** The original data that was passed to this error instance. */
  data$: ProjectErrorResponseData;

  constructor(
    err: ProjectErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ProjectErrorResponse";
  }
}

/** @internal */
export const ProjectErrorResponse$inboundSchema: z.ZodType<
  ProjectErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ProjectErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ProjectErrorResponse$Outbound = {
  message: string;
};

/** @internal */
export const ProjectErrorResponse$outboundSchema: z.ZodType<
  ProjectErrorResponse$Outbound,
  z.ZodTypeDef,
  ProjectErrorResponse
> = z.instanceof(ProjectErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectErrorResponse$ {
  /** @deprecated use `ProjectErrorResponse$inboundSchema` instead. */
  export const inboundSchema = ProjectErrorResponse$inboundSchema;
  /** @deprecated use `ProjectErrorResponse$outboundSchema` instead. */
  export const outboundSchema = ProjectErrorResponse$outboundSchema;
  /** @deprecated use `ProjectErrorResponse$Outbound` instead. */
  export type Outbound = ProjectErrorResponse$Outbound;
}
