/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Release error schema.
 */
export type ReleaseErrorData = {
  message: string;
};

/**
 * Release error schema.
 */
export class ReleaseError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: ReleaseErrorData;

  constructor(
    err: ReleaseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ReleaseError";
  }
}

/** @internal */
export const ReleaseError$inboundSchema: z.ZodType<
  ReleaseError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ReleaseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ReleaseError$Outbound = {
  message: string;
};

/** @internal */
export const ReleaseError$outboundSchema: z.ZodType<
  ReleaseError$Outbound,
  z.ZodTypeDef,
  ReleaseError
> = z.instanceof(ReleaseError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReleaseError$ {
  /** @deprecated use `ReleaseError$inboundSchema` instead. */
  export const inboundSchema = ReleaseError$inboundSchema;
  /** @deprecated use `ReleaseError$outboundSchema` instead. */
  export const outboundSchema = ReleaseError$outboundSchema;
  /** @deprecated use `ReleaseError$Outbound` instead. */
  export type Outbound = ReleaseError$Outbound;
}
