/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { NestError } from "./nesterror.js";

/**
 * Repository error schema.
 */
export type RepositoryErrorData = {
  message: string;
};

/**
 * Repository error schema.
 */
export class RepositoryError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: RepositoryErrorData;

  constructor(
    err: RepositoryErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "RepositoryError";
  }
}

/** @internal */
export const RepositoryError$inboundSchema: z.ZodType<
  RepositoryError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RepositoryError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type RepositoryError$Outbound = {
  message: string;
};

/** @internal */
export const RepositoryError$outboundSchema: z.ZodType<
  RepositoryError$Outbound,
  z.ZodTypeDef,
  RepositoryError
> = z.instanceof(RepositoryError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RepositoryError$ {
  /** @deprecated use `RepositoryError$inboundSchema` instead. */
  export const inboundSchema = RepositoryError$inboundSchema;
  /** @deprecated use `RepositoryError$outboundSchema` instead. */
  export const outboundSchema = RepositoryError$outboundSchema;
  /** @deprecated use `RepositoryError$Outbound` instead. */
  export type Outbound = RepositoryError$Outbound;
}
