/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { NestError } from "./nesterror.js";

/**
 * Snapshot error schema.
 */
export type SnapshotErrorData = {
  message: string;
};

/**
 * Snapshot error schema.
 */
export class SnapshotError extends NestError {
  /** The original data that was passed to this error instance. */
  data$: SnapshotErrorData;

  constructor(
    err: SnapshotErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "SnapshotError";
  }
}

/** @internal */
export const SnapshotError$inboundSchema: z.ZodType<
  SnapshotError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new SnapshotError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
