/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { NestError } from "./nesterror.js";

/**
 * Schema for validation error.
 */
export type ValidationErrorSchemaData = {
  message: string;
  errors?: models.Errors | null | undefined;
};

/**
 * Schema for validation error.
 */
export class ValidationErrorSchema extends NestError {
  errors?: models.Errors | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ValidationErrorSchemaData;

  constructor(
    err: ValidationErrorSchemaData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.errors != null) this.errors = err.errors;

    this.name = "ValidationErrorSchema";
  }
}

/** @internal */
export const ValidationErrorSchema$inboundSchema: z.ZodType<
  ValidationErrorSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  errors: z.nullable(z.lazy(() => models.Errors$inboundSchema)).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ValidationErrorSchema(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
