/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chaptersGetChapter } from "../funcs/chaptersGetChapter.js";
import { chaptersListChapters } from "../funcs/chaptersListChapters.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chapters extends ClientSDK {
  /**
   * List chapters
   *
   * @remarks
   * Retrieve a paginated list of OWASP chapters.
   */
  async listChapters(
    request?: operations.ListChaptersRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedChapterSchema> {
    return unwrapAsync(chaptersListChapters(
      this,
      request,
      options,
    ));
  }

  /**
   * Get chapter
   *
   * @remarks
   * Retrieve chapter details.
   */
  async getChapter(
    request: operations.GetChapterRequest,
    options?: RequestOptions,
  ): Promise<models.ChapterSchema> {
    return unwrapAsync(chaptersGetChapter(
      this,
      request,
      options,
    ));
  }
}
