/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chaptersAppsApiRestV0ChapterGetChapter } from "../funcs/chaptersAppsApiRestV0ChapterGetChapter.js";
import { chaptersAppsApiRestV0ChapterListChapters } from "../funcs/chaptersAppsApiRestV0ChapterListChapters.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chapters extends ClientSDK {
  /**
   * List chapters
   *
   * @remarks
   * Retrieve a paginated list of OWASP chapters.
   */
  async appsApiRestV0ChapterListChapters(
    request?: operations.AppsApiRestV0ChapterListChaptersRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedChapterSchema> {
    return unwrapAsync(chaptersAppsApiRestV0ChapterListChapters(
      this,
      request,
      options,
    ));
  }

  /**
   * Get chapter
   *
   * @remarks
   * Retrieve chapter details.
   */
  async appsApiRestV0ChapterGetChapter(
    request: operations.AppsApiRestV0ChapterGetChapterRequest,
    options?: RequestOptions,
  ): Promise<models.ChapterSchema> {
    return unwrapAsync(chaptersAppsApiRestV0ChapterGetChapter(
      this,
      request,
      options,
    ));
  }
}
