/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { committeesGetCommittee } from "../funcs/committeesGetCommittee.js";
import { committeesListCommittees } from "../funcs/committeesListCommittees.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Committees extends ClientSDK {
  /**
   * List committees
   *
   * @remarks
   * Retrieve a paginated list of OWASP committees.
   */
  async listCommittees(
    request?: operations.ListCommitteesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedCommitteeSchema> {
    return unwrapAsync(committeesListCommittees(
      this,
      request,
      options,
    ));
  }

  /**
   * Get committee
   *
   * @remarks
   * Retrieve committee details.
   */
  async getCommittee(
    request: operations.GetCommitteeRequest,
    options?: RequestOptions,
  ): Promise<models.CommitteeSchema> {
    return unwrapAsync(committeesGetCommittee(
      this,
      request,
      options,
    ));
  }
}
