/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsAppsApiRestV0EventListEvents } from "../funcs/eventsAppsApiRestV0EventListEvents.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * List events
   *
   * @remarks
   * Retrieve a paginated list of OWASP events.
   */
  async appsApiRestV0EventListEvents(
    request?: operations.AppsApiRestV0EventListEventsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedEventSchema> {
    return unwrapAsync(eventsAppsApiRestV0EventListEvents(
      this,
      request,
      options,
    ));
  }
}
