/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsListEvents } from "../funcs/eventsListEvents.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * List events
   *
   * @remarks
   * Retrieve a paginated list of OWASP events.
   */
  async listEvents(
    request?: operations.ListEventsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedEventSchema> {
    return unwrapAsync(eventsListEvents(
      this,
      request,
      options,
    ));
  }
}
