/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { issuesGetIssue } from "../funcs/issuesGetIssue.js";
import { issuesListIssues } from "../funcs/issuesListIssues.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Issues extends ClientSDK {
  /**
   * List issues
   *
   * @remarks
   * Retrieve a paginated list of GitHub issues.
   */
  async listIssues(
    request?: operations.ListIssuesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedIssue> {
    return unwrapAsync(issuesListIssues(
      this,
      request,
      options,
    ));
  }

  /**
   * Get issue
   *
   * @remarks
   * Retrieve a specific GitHub issue by organization, repository, and issue number.
   */
  async getIssue(
    request: operations.GetIssueRequest,
    options?: RequestOptions,
  ): Promise<models.IssueDetail> {
    return unwrapAsync(issuesGetIssue(
      this,
      request,
      options,
    ));
  }
}
