/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { issuesListIssues } from "../funcs/issuesListIssues.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Issues extends ClientSDK {
  /**
   * List issues
   *
   * @remarks
   * Retrieve a paginated list of GitHub issues.
   */
  async listIssues(
    request?: operations.ListIssuesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedIssueSchema> {
    return unwrapAsync(issuesListIssues(
      this,
      request,
      options,
    ));
  }
}
