/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsAppsApiRestV0ProjectGetProject } from "../funcs/projectsAppsApiRestV0ProjectGetProject.js";
import { projectsAppsApiRestV0ProjectListProjects } from "../funcs/projectsAppsApiRestV0ProjectListProjects.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List projects
   *
   * @remarks
   * Retrieve a paginated list of OWASP projects.
   */
  async appsApiRestV0ProjectListProjects(
    request?: operations.AppsApiRestV0ProjectListProjectsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedProjectSchema> {
    return unwrapAsync(projectsAppsApiRestV0ProjectListProjects(
      this,
      request,
      options,
    ));
  }

  /**
   * Get project
   *
   * @remarks
   * Retrieve project details.
   */
  async appsApiRestV0ProjectGetProject(
    request: operations.AppsApiRestV0ProjectGetProjectRequest,
    options?: RequestOptions,
  ): Promise<models.ProjectSchema> {
    return unwrapAsync(projectsAppsApiRestV0ProjectGetProject(
      this,
      request,
      options,
    ));
  }
}
