/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsListProjects } from "../funcs/projectsListProjects.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List projects
   *
   * @remarks
   * Retrieve a paginated list of OWASP projects.
   */
  async listProjects(
    request?: operations.ListProjectsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedProjectSchema> {
    return unwrapAsync(projectsListProjects(
      this,
      request,
      options,
    ));
  }
}
