/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { releasesListReleases } from "../funcs/releasesListReleases.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Releases extends ClientSDK {
  /**
   * List releases
   *
   * @remarks
   * Retrieve a paginated list of GitHub releases.
   */
  async listReleases(
    request?: operations.ListReleasesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedReleaseSchema> {
    return unwrapAsync(releasesListReleases(
      this,
      request,
      options,
    ));
  }
}
