/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Chapters } from "./chapters.js";
import { Committees } from "./committees.js";
import { Community } from "./community.js";
import { Events } from "./events.js";
import { Issues } from "./issues.js";
import { Projects } from "./projects.js";
import { Releases } from "./releases.js";
import { Repositories } from "./repositories.js";
import { Sponsors } from "./sponsors.js";

export class Nest extends ClientSDK {
  private _chapters?: Chapters;
  get chapters(): Chapters {
    return (this._chapters ??= new Chapters(this._options));
  }

  private _committees?: Committees;
  get committees(): Committees {
    return (this._committees ??= new Committees(this._options));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _issues?: Issues;
  get issues(): Issues {
    return (this._issues ??= new Issues(this._options));
  }

  private _community?: Community;
  get community(): Community {
    return (this._community ??= new Community(this._options));
  }

  private _projects?: Projects;
  get projects(): Projects {
    return (this._projects ??= new Projects(this._options));
  }

  private _releases?: Releases;
  get releases(): Releases {
    return (this._releases ??= new Releases(this._options));
  }

  private _repositories?: Repositories;
  get repositories(): Repositories {
    return (this._repositories ??= new Repositories(this._options));
  }

  private _sponsors?: Sponsors;
  get sponsors(): Sponsors {
    return (this._sponsors ??= new Sponsors(this._options));
  }
}
