/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sponsorsGetSponsor } from "../funcs/sponsorsGetSponsor.js";
import { sponsorsListSponsors } from "../funcs/sponsorsListSponsors.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sponsors extends ClientSDK {
  /**
   * List sponsors
   *
   * @remarks
   * Retrieve a paginated list of OWASP sponsors.
   */
  async listSponsors(
    request?: operations.ListSponsorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PagedSponsor> {
    return unwrapAsync(sponsorsListSponsors(
      this,
      request,
      options,
    ));
  }

  /**
   * Get sponsor
   *
   * @remarks
   * Retrieve a sponsor details.
   */
  async getSponsor(
    request: operations.GetSponsorRequest,
    options?: RequestOptions,
  ): Promise<models.SponsorDetail> {
    return unwrapAsync(sponsorsGetSponsor(
      this,
      request,
      options,
    ));
  }
}
