/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the owasp-nest SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx chaptersListChapters.example.ts
 */

import { Nest } from "owasp-nest";

const nest = new Nest({
  apiKeyHeader: process.env["NEST_API_KEY_HEADER"] ?? "",
});

async function main() {
  const result = await nest.chapters.listChapters({
    country: "India",
    region: "Asia",
  });

  console.log(result);
}

main().catch(console.error);
