/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppsApiRestV0ProjectGetProjectRequest = {
  projectId: string;
};

/** @internal */
export const AppsApiRestV0ProjectGetProjectRequest$inboundSchema: z.ZodType<
  AppsApiRestV0ProjectGetProjectRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "project_id": "projectId",
  });
});

/** @internal */
export type AppsApiRestV0ProjectGetProjectRequest$Outbound = {
  project_id: string;
};

/** @internal */
export const AppsApiRestV0ProjectGetProjectRequest$outboundSchema: z.ZodType<
  AppsApiRestV0ProjectGetProjectRequest$Outbound,
  z.ZodTypeDef,
  AppsApiRestV0ProjectGetProjectRequest
> = z.object({
  projectId: z.string(),
}).transform((v) => {
  return remap$(v, {
    projectId: "project_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppsApiRestV0ProjectGetProjectRequest$ {
  /** @deprecated use `AppsApiRestV0ProjectGetProjectRequest$inboundSchema` instead. */
  export const inboundSchema =
    AppsApiRestV0ProjectGetProjectRequest$inboundSchema;
  /** @deprecated use `AppsApiRestV0ProjectGetProjectRequest$outboundSchema` instead. */
  export const outboundSchema =
    AppsApiRestV0ProjectGetProjectRequest$outboundSchema;
  /** @deprecated use `AppsApiRestV0ProjectGetProjectRequest$Outbound` instead. */
  export type Outbound = AppsApiRestV0ProjectGetProjectRequest$Outbound;
}

export function appsApiRestV0ProjectGetProjectRequestToJSON(
  appsApiRestV0ProjectGetProjectRequest: AppsApiRestV0ProjectGetProjectRequest,
): string {
  return JSON.stringify(
    AppsApiRestV0ProjectGetProjectRequest$outboundSchema.parse(
      appsApiRestV0ProjectGetProjectRequest,
    ),
  );
}

export function appsApiRestV0ProjectGetProjectRequestFromJSON(
  jsonString: string,
): SafeParseResult<AppsApiRestV0ProjectGetProjectRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppsApiRestV0ProjectGetProjectRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppsApiRestV0ProjectGetProjectRequest' from JSON`,
  );
}
