/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Ordering field
 */
export const AppsApiRestV0OrganizationListOrganizationOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type AppsApiRestV0OrganizationListOrganizationOrdering = ClosedEnum<
  typeof AppsApiRestV0OrganizationListOrganizationOrdering
>;

export type AppsApiRestV0OrganizationListOrganizationRequest = {
  /**
   * Location of the organization
   */
  location?: string | null | undefined;
  /**
   * Ordering field
   */
  ordering?:
    | AppsApiRestV0OrganizationListOrganizationOrdering
    | null
    | undefined;
  page?: number | undefined;
  pageSize?: number | null | undefined;
};

/** @internal */
export const AppsApiRestV0OrganizationListOrganizationOrdering$inboundSchema:
  z.ZodNativeEnum<typeof AppsApiRestV0OrganizationListOrganizationOrdering> = z
    .nativeEnum(AppsApiRestV0OrganizationListOrganizationOrdering);

/** @internal */
export const AppsApiRestV0OrganizationListOrganizationOrdering$outboundSchema:
  z.ZodNativeEnum<typeof AppsApiRestV0OrganizationListOrganizationOrdering> =
    AppsApiRestV0OrganizationListOrganizationOrdering$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppsApiRestV0OrganizationListOrganizationOrdering$ {
  /** @deprecated use `AppsApiRestV0OrganizationListOrganizationOrdering$inboundSchema` instead. */
  export const inboundSchema =
    AppsApiRestV0OrganizationListOrganizationOrdering$inboundSchema;
  /** @deprecated use `AppsApiRestV0OrganizationListOrganizationOrdering$outboundSchema` instead. */
  export const outboundSchema =
    AppsApiRestV0OrganizationListOrganizationOrdering$outboundSchema;
}

/** @internal */
export const AppsApiRestV0OrganizationListOrganizationRequest$inboundSchema:
  z.ZodType<
    AppsApiRestV0OrganizationListOrganizationRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    location: z.nullable(z.string()).optional(),
    ordering: z.nullable(
      AppsApiRestV0OrganizationListOrganizationOrdering$inboundSchema,
    ).optional(),
    page: z.number().int().default(1),
    page_size: z.nullable(z.number().int()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "page_size": "pageSize",
    });
  });

/** @internal */
export type AppsApiRestV0OrganizationListOrganizationRequest$Outbound = {
  location?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size?: number | null | undefined;
};

/** @internal */
export const AppsApiRestV0OrganizationListOrganizationRequest$outboundSchema:
  z.ZodType<
    AppsApiRestV0OrganizationListOrganizationRequest$Outbound,
    z.ZodTypeDef,
    AppsApiRestV0OrganizationListOrganizationRequest
  > = z.object({
    location: z.nullable(z.string()).optional(),
    ordering: z.nullable(
      AppsApiRestV0OrganizationListOrganizationOrdering$outboundSchema,
    ).optional(),
    page: z.number().int().default(1),
    pageSize: z.nullable(z.number().int()).optional(),
  }).transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppsApiRestV0OrganizationListOrganizationRequest$ {
  /** @deprecated use `AppsApiRestV0OrganizationListOrganizationRequest$inboundSchema` instead. */
  export const inboundSchema =
    AppsApiRestV0OrganizationListOrganizationRequest$inboundSchema;
  /** @deprecated use `AppsApiRestV0OrganizationListOrganizationRequest$outboundSchema` instead. */
  export const outboundSchema =
    AppsApiRestV0OrganizationListOrganizationRequest$outboundSchema;
  /** @deprecated use `AppsApiRestV0OrganizationListOrganizationRequest$Outbound` instead. */
  export type Outbound =
    AppsApiRestV0OrganizationListOrganizationRequest$Outbound;
}

export function appsApiRestV0OrganizationListOrganizationRequestToJSON(
  appsApiRestV0OrganizationListOrganizationRequest:
    AppsApiRestV0OrganizationListOrganizationRequest,
): string {
  return JSON.stringify(
    AppsApiRestV0OrganizationListOrganizationRequest$outboundSchema.parse(
      appsApiRestV0OrganizationListOrganizationRequest,
    ),
  );
}

export function appsApiRestV0OrganizationListOrganizationRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  AppsApiRestV0OrganizationListOrganizationRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppsApiRestV0OrganizationListOrganizationRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppsApiRestV0OrganizationListOrganizationRequest' from JSON`,
  );
}
