/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppsApiRestV0ChapterGetChapterRequest = {
  chapterId: string;
};

/** @internal */
export const AppsApiRestV0ChapterGetChapterRequest$inboundSchema: z.ZodType<
  AppsApiRestV0ChapterGetChapterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chapter_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "chapter_id": "chapterId",
  });
});

/** @internal */
export type AppsApiRestV0ChapterGetChapterRequest$Outbound = {
  chapter_id: string;
};

/** @internal */
export const AppsApiRestV0ChapterGetChapterRequest$outboundSchema: z.ZodType<
  AppsApiRestV0ChapterGetChapterRequest$Outbound,
  z.ZodTypeDef,
  AppsApiRestV0ChapterGetChapterRequest
> = z.object({
  chapterId: z.string(),
}).transform((v) => {
  return remap$(v, {
    chapterId: "chapter_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppsApiRestV0ChapterGetChapterRequest$ {
  /** @deprecated use `AppsApiRestV0ChapterGetChapterRequest$inboundSchema` instead. */
  export const inboundSchema =
    AppsApiRestV0ChapterGetChapterRequest$inboundSchema;
  /** @deprecated use `AppsApiRestV0ChapterGetChapterRequest$outboundSchema` instead. */
  export const outboundSchema =
    AppsApiRestV0ChapterGetChapterRequest$outboundSchema;
  /** @deprecated use `AppsApiRestV0ChapterGetChapterRequest$Outbound` instead. */
  export type Outbound = AppsApiRestV0ChapterGetChapterRequest$Outbound;
}

export function appsApiRestV0ChapterGetChapterRequestToJSON(
  appsApiRestV0ChapterGetChapterRequest: AppsApiRestV0ChapterGetChapterRequest,
): string {
  return JSON.stringify(
    AppsApiRestV0ChapterGetChapterRequest$outboundSchema.parse(
      appsApiRestV0ChapterGetChapterRequest,
    ),
  );
}

export function appsApiRestV0ChapterGetChapterRequestFromJSON(
  jsonString: string,
): SafeParseResult<AppsApiRestV0ChapterGetChapterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppsApiRestV0ChapterGetChapterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppsApiRestV0ChapterGetChapterRequest' from JSON`,
  );
}
