/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppsApiRestV0CommitteeGetChapterRequest = {
  committeeId: string;
};

/** @internal */
export const AppsApiRestV0CommitteeGetChapterRequest$inboundSchema: z.ZodType<
  AppsApiRestV0CommitteeGetChapterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  committee_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "committee_id": "committeeId",
  });
});

/** @internal */
export type AppsApiRestV0CommitteeGetChapterRequest$Outbound = {
  committee_id: string;
};

/** @internal */
export const AppsApiRestV0CommitteeGetChapterRequest$outboundSchema: z.ZodType<
  AppsApiRestV0CommitteeGetChapterRequest$Outbound,
  z.ZodTypeDef,
  AppsApiRestV0CommitteeGetChapterRequest
> = z.object({
  committeeId: z.string(),
}).transform((v) => {
  return remap$(v, {
    committeeId: "committee_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppsApiRestV0CommitteeGetChapterRequest$ {
  /** @deprecated use `AppsApiRestV0CommitteeGetChapterRequest$inboundSchema` instead. */
  export const inboundSchema =
    AppsApiRestV0CommitteeGetChapterRequest$inboundSchema;
  /** @deprecated use `AppsApiRestV0CommitteeGetChapterRequest$outboundSchema` instead. */
  export const outboundSchema =
    AppsApiRestV0CommitteeGetChapterRequest$outboundSchema;
  /** @deprecated use `AppsApiRestV0CommitteeGetChapterRequest$Outbound` instead. */
  export type Outbound = AppsApiRestV0CommitteeGetChapterRequest$Outbound;
}

export function appsApiRestV0CommitteeGetChapterRequestToJSON(
  appsApiRestV0CommitteeGetChapterRequest:
    AppsApiRestV0CommitteeGetChapterRequest,
): string {
  return JSON.stringify(
    AppsApiRestV0CommitteeGetChapterRequest$outboundSchema.parse(
      appsApiRestV0CommitteeGetChapterRequest,
    ),
  );
}

export function appsApiRestV0CommitteeGetChapterRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  AppsApiRestV0CommitteeGetChapterRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppsApiRestV0CommitteeGetChapterRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppsApiRestV0CommitteeGetChapterRequest' from JSON`,
  );
}
