/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Ordering field
 */
export const AppsApiRestV0ChapterListChaptersOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type AppsApiRestV0ChapterListChaptersOrdering = ClosedEnum<
  typeof AppsApiRestV0ChapterListChaptersOrdering
>;

export type AppsApiRestV0ChapterListChaptersRequest = {
  /**
   * Country of the chapter
   */
  country?: string | null | undefined;
  /**
   * Region of the chapter
   */
  region?: string | null | undefined;
  /**
   * Ordering field
   */
  ordering?: AppsApiRestV0ChapterListChaptersOrdering | null | undefined;
  page?: number | undefined;
  pageSize?: number | null | undefined;
};

/** @internal */
export const AppsApiRestV0ChapterListChaptersOrdering$inboundSchema:
  z.ZodNativeEnum<typeof AppsApiRestV0ChapterListChaptersOrdering> = z
    .nativeEnum(AppsApiRestV0ChapterListChaptersOrdering);

/** @internal */
export const AppsApiRestV0ChapterListChaptersOrdering$outboundSchema:
  z.ZodNativeEnum<typeof AppsApiRestV0ChapterListChaptersOrdering> =
    AppsApiRestV0ChapterListChaptersOrdering$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppsApiRestV0ChapterListChaptersOrdering$ {
  /** @deprecated use `AppsApiRestV0ChapterListChaptersOrdering$inboundSchema` instead. */
  export const inboundSchema =
    AppsApiRestV0ChapterListChaptersOrdering$inboundSchema;
  /** @deprecated use `AppsApiRestV0ChapterListChaptersOrdering$outboundSchema` instead. */
  export const outboundSchema =
    AppsApiRestV0ChapterListChaptersOrdering$outboundSchema;
}

/** @internal */
export const AppsApiRestV0ChapterListChaptersRequest$inboundSchema: z.ZodType<
  AppsApiRestV0ChapterListChaptersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  ordering: z.nullable(AppsApiRestV0ChapterListChaptersOrdering$inboundSchema)
    .optional(),
  page: z.number().int().default(1),
  page_size: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
  });
});

/** @internal */
export type AppsApiRestV0ChapterListChaptersRequest$Outbound = {
  country?: string | null | undefined;
  region?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size?: number | null | undefined;
};

/** @internal */
export const AppsApiRestV0ChapterListChaptersRequest$outboundSchema: z.ZodType<
  AppsApiRestV0ChapterListChaptersRequest$Outbound,
  z.ZodTypeDef,
  AppsApiRestV0ChapterListChaptersRequest
> = z.object({
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  ordering: z.nullable(AppsApiRestV0ChapterListChaptersOrdering$outboundSchema)
    .optional(),
  page: z.number().int().default(1),
  pageSize: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppsApiRestV0ChapterListChaptersRequest$ {
  /** @deprecated use `AppsApiRestV0ChapterListChaptersRequest$inboundSchema` instead. */
  export const inboundSchema =
    AppsApiRestV0ChapterListChaptersRequest$inboundSchema;
  /** @deprecated use `AppsApiRestV0ChapterListChaptersRequest$outboundSchema` instead. */
  export const outboundSchema =
    AppsApiRestV0ChapterListChaptersRequest$outboundSchema;
  /** @deprecated use `AppsApiRestV0ChapterListChaptersRequest$Outbound` instead. */
  export type Outbound = AppsApiRestV0ChapterListChaptersRequest$Outbound;
}

export function appsApiRestV0ChapterListChaptersRequestToJSON(
  appsApiRestV0ChapterListChaptersRequest:
    AppsApiRestV0ChapterListChaptersRequest,
): string {
  return JSON.stringify(
    AppsApiRestV0ChapterListChaptersRequest$outboundSchema.parse(
      appsApiRestV0ChapterListChaptersRequest,
    ),
  );
}

export function appsApiRestV0ChapterListChaptersRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  AppsApiRestV0ChapterListChaptersRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppsApiRestV0ChapterListChaptersRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppsApiRestV0ChapterListChaptersRequest' from JSON`,
  );
}
