/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetChapterRequest = {
  chapterId: string;
};

/** @internal */
export type GetChapterRequest$Outbound = {
  chapter_id: string;
};

/** @internal */
export const GetChapterRequest$outboundSchema: z.ZodType<
  GetChapterRequest$Outbound,
  z.ZodTypeDef,
  GetChapterRequest
> = z.object({
  chapterId: z.string(),
}).transform((v) => {
  return remap$(v, {
    chapterId: "chapter_id",
  });
});

export function getChapterRequestToJSON(
  getChapterRequest: GetChapterRequest,
): string {
  return JSON.stringify(
    GetChapterRequest$outboundSchema.parse(getChapterRequest),
  );
}
