/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetCommitteeRequest = {
  committeeId: string;
};

/** @internal */
export type GetCommitteeRequest$Outbound = {
  committee_id: string;
};

/** @internal */
export const GetCommitteeRequest$outboundSchema: z.ZodType<
  GetCommitteeRequest$Outbound,
  z.ZodTypeDef,
  GetCommitteeRequest
> = z.object({
  committeeId: z.string(),
}).transform((v) => {
  return remap$(v, {
    committeeId: "committee_id",
  });
});

export function getCommitteeRequestToJSON(
  getCommitteeRequest: GetCommitteeRequest,
): string {
  return JSON.stringify(
    GetCommitteeRequest$outboundSchema.parse(getCommitteeRequest),
  );
}
