/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCommitteeRequest = {
  committeeId: string;
};

/** @internal */
export const GetCommitteeRequest$inboundSchema: z.ZodType<
  GetCommitteeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  committee_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "committee_id": "committeeId",
  });
});

/** @internal */
export type GetCommitteeRequest$Outbound = {
  committee_id: string;
};

/** @internal */
export const GetCommitteeRequest$outboundSchema: z.ZodType<
  GetCommitteeRequest$Outbound,
  z.ZodTypeDef,
  GetCommitteeRequest
> = z.object({
  committeeId: z.string(),
}).transform((v) => {
  return remap$(v, {
    committeeId: "committee_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCommitteeRequest$ {
  /** @deprecated use `GetCommitteeRequest$inboundSchema` instead. */
  export const inboundSchema = GetCommitteeRequest$inboundSchema;
  /** @deprecated use `GetCommitteeRequest$outboundSchema` instead. */
  export const outboundSchema = GetCommitteeRequest$outboundSchema;
  /** @deprecated use `GetCommitteeRequest$Outbound` instead. */
  export type Outbound = GetCommitteeRequest$Outbound;
}

export function getCommitteeRequestToJSON(
  getCommitteeRequest: GetCommitteeRequest,
): string {
  return JSON.stringify(
    GetCommitteeRequest$outboundSchema.parse(getCommitteeRequest),
  );
}

export function getCommitteeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCommitteeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCommitteeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCommitteeRequest' from JSON`,
  );
}
