/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetEventRequest = {
  eventId: string;
};

/** @internal */
export type GetEventRequest$Outbound = {
  event_id: string;
};

/** @internal */
export const GetEventRequest$outboundSchema: z.ZodType<
  GetEventRequest$Outbound,
  z.ZodTypeDef,
  GetEventRequest
> = z.object({
  eventId: z.string(),
}).transform((v) => {
  return remap$(v, {
    eventId: "event_id",
  });
});

export function getEventRequestToJSON(
  getEventRequest: GetEventRequest,
): string {
  return JSON.stringify(GetEventRequest$outboundSchema.parse(getEventRequest));
}
