/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetIssueRequest = {
  organizationId: string;
  repositoryId: string;
  issueId: number;
};

/** @internal */
export type GetIssueRequest$Outbound = {
  organization_id: string;
  repository_id: string;
  issue_id: number;
};

/** @internal */
export const GetIssueRequest$outboundSchema: z.ZodType<
  GetIssueRequest$Outbound,
  z.ZodTypeDef,
  GetIssueRequest
> = z.object({
  organizationId: z.string(),
  repositoryId: z.string(),
  issueId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    repositoryId: "repository_id",
    issueId: "issue_id",
  });
});

export function getIssueRequestToJSON(
  getIssueRequest: GetIssueRequest,
): string {
  return JSON.stringify(GetIssueRequest$outboundSchema.parse(getIssueRequest));
}
