/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetMilestoneRequest = {
  organizationId: string;
  repositoryId: string;
  milestoneId: number;
};

/** @internal */
export type GetMilestoneRequest$Outbound = {
  organization_id: string;
  repository_id: string;
  milestone_id: number;
};

/** @internal */
export const GetMilestoneRequest$outboundSchema: z.ZodType<
  GetMilestoneRequest$Outbound,
  z.ZodTypeDef,
  GetMilestoneRequest
> = z.object({
  organizationId: z.string(),
  repositoryId: z.string(),
  milestoneId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    repositoryId: "repository_id",
    milestoneId: "milestone_id",
  });
});

export function getMilestoneRequestToJSON(
  getMilestoneRequest: GetMilestoneRequest,
): string {
  return JSON.stringify(
    GetMilestoneRequest$outboundSchema.parse(getMilestoneRequest),
  );
}
