/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetOrganizationRequest = {
  organizationId: string;
};

/** @internal */
export type GetOrganizationRequest$Outbound = {
  organization_id: string;
};

/** @internal */
export const GetOrganizationRequest$outboundSchema: z.ZodType<
  GetOrganizationRequest$Outbound,
  z.ZodTypeDef,
  GetOrganizationRequest
> = z.object({
  organizationId: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
  });
});

export function getOrganizationRequestToJSON(
  getOrganizationRequest: GetOrganizationRequest,
): string {
  return JSON.stringify(
    GetOrganizationRequest$outboundSchema.parse(getOrganizationRequest),
  );
}
