/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetProjectRequest = {
  projectId: string;
};

/** @internal */
export type GetProjectRequest$Outbound = {
  project_id: string;
};

/** @internal */
export const GetProjectRequest$outboundSchema: z.ZodType<
  GetProjectRequest$Outbound,
  z.ZodTypeDef,
  GetProjectRequest
> = z.object({
  projectId: z.string(),
}).transform((v) => {
  return remap$(v, {
    projectId: "project_id",
  });
});

export function getProjectRequestToJSON(
  getProjectRequest: GetProjectRequest,
): string {
  return JSON.stringify(
    GetProjectRequest$outboundSchema.parse(getProjectRequest),
  );
}
