/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetReleaseRequest = {
  organizationId: string;
  repositoryId: string;
  releaseId: string;
};

/** @internal */
export type GetReleaseRequest$Outbound = {
  organization_id: string;
  repository_id: string;
  release_id: string;
};

/** @internal */
export const GetReleaseRequest$outboundSchema: z.ZodType<
  GetReleaseRequest$Outbound,
  z.ZodTypeDef,
  GetReleaseRequest
> = z.object({
  organizationId: z.string(),
  repositoryId: z.string(),
  releaseId: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    repositoryId: "repository_id",
    releaseId: "release_id",
  });
});

export function getReleaseRequestToJSON(
  getReleaseRequest: GetReleaseRequest,
): string {
  return JSON.stringify(
    GetReleaseRequest$outboundSchema.parse(getReleaseRequest),
  );
}
