/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetReleaseRequest = {
  organizationId: string;
  repositoryId: string;
  releaseId: string;
};

/** @internal */
export const GetReleaseRequest$inboundSchema: z.ZodType<
  GetReleaseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization_id: z.string(),
  repository_id: z.string(),
  release_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "organization_id": "organizationId",
    "repository_id": "repositoryId",
    "release_id": "releaseId",
  });
});

/** @internal */
export type GetReleaseRequest$Outbound = {
  organization_id: string;
  repository_id: string;
  release_id: string;
};

/** @internal */
export const GetReleaseRequest$outboundSchema: z.ZodType<
  GetReleaseRequest$Outbound,
  z.ZodTypeDef,
  GetReleaseRequest
> = z.object({
  organizationId: z.string(),
  repositoryId: z.string(),
  releaseId: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    repositoryId: "repository_id",
    releaseId: "release_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetReleaseRequest$ {
  /** @deprecated use `GetReleaseRequest$inboundSchema` instead. */
  export const inboundSchema = GetReleaseRequest$inboundSchema;
  /** @deprecated use `GetReleaseRequest$outboundSchema` instead. */
  export const outboundSchema = GetReleaseRequest$outboundSchema;
  /** @deprecated use `GetReleaseRequest$Outbound` instead. */
  export type Outbound = GetReleaseRequest$Outbound;
}

export function getReleaseRequestToJSON(
  getReleaseRequest: GetReleaseRequest,
): string {
  return JSON.stringify(
    GetReleaseRequest$outboundSchema.parse(getReleaseRequest),
  );
}

export function getReleaseRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetReleaseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetReleaseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetReleaseRequest' from JSON`,
  );
}
