/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetRepositoryRequest = {
  organizationId: string;
  repositoryId: string;
};

/** @internal */
export type GetRepositoryRequest$Outbound = {
  organization_id: string;
  repository_id: string;
};

/** @internal */
export const GetRepositoryRequest$outboundSchema: z.ZodType<
  GetRepositoryRequest$Outbound,
  z.ZodTypeDef,
  GetRepositoryRequest
> = z.object({
  organizationId: z.string(),
  repositoryId: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    repositoryId: "repository_id",
  });
});

export function getRepositoryRequestToJSON(
  getRepositoryRequest: GetRepositoryRequest,
): string {
  return JSON.stringify(
    GetRepositoryRequest$outboundSchema.parse(getRepositoryRequest),
  );
}
