/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSponsorRequest = {
  sponsorId: string;
};

/** @internal */
export type GetSponsorRequest$Outbound = {
  sponsor_id: string;
};

/** @internal */
export const GetSponsorRequest$outboundSchema: z.ZodType<
  GetSponsorRequest$Outbound,
  z.ZodTypeDef,
  GetSponsorRequest
> = z.object({
  sponsorId: z.string(),
}).transform((v) => {
  return remap$(v, {
    sponsorId: "sponsor_id",
  });
});

export function getSponsorRequestToJSON(
  getSponsorRequest: GetSponsorRequest,
): string {
  return JSON.stringify(
    GetSponsorRequest$outboundSchema.parse(getSponsorRequest),
  );
}
