/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSnapshotRequest = {
  snapshotId: string;
};

/** @internal */
export type GetSnapshotRequest$Outbound = {
  snapshot_id: string;
};

/** @internal */
export const GetSnapshotRequest$outboundSchema: z.ZodType<
  GetSnapshotRequest$Outbound,
  z.ZodTypeDef,
  GetSnapshotRequest
> = z.object({
  snapshotId: z.string(),
}).transform((v) => {
  return remap$(v, {
    snapshotId: "snapshot_id",
  });
});

export function getSnapshotRequestToJSON(
  getSnapshotRequest: GetSnapshotRequest,
): string {
  return JSON.stringify(
    GetSnapshotRequest$outboundSchema.parse(getSnapshotRequest),
  );
}
