/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListOrganizationsOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListOrganizationsOrdering = ClosedEnum<
  typeof ListOrganizationsOrdering
>;

export type ListOrganizationsRequest = {
  /**
   * Location of the organization
   */
  location?: string | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListOrganizationsOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListOrganizationsOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListOrganizationsOrdering
> = z.nativeEnum(ListOrganizationsOrdering);

/** @internal */
export type ListOrganizationsRequest$Outbound = {
  location?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListOrganizationsRequest$outboundSchema: z.ZodType<
  ListOrganizationsRequest$Outbound,
  z.ZodTypeDef,
  ListOrganizationsRequest
> = z.object({
  location: z.nullable(z.string()).optional(),
  ordering: z.nullable(ListOrganizationsOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listOrganizationsRequestToJSON(
  listOrganizationsRequest: ListOrganizationsRequest,
): string {
  return JSON.stringify(
    ListOrganizationsRequest$outboundSchema.parse(listOrganizationsRequest),
  );
}
