/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Ordering field
 */
export const ListIssuesOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListIssuesOrdering = ClosedEnum<typeof ListIssuesOrdering>;

export type ListIssuesRequest = {
  /**
   * State of the issue
   */
  state?: models.State | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListIssuesOrdering | null | undefined;
  page?: number | undefined;
  pageSize?: number | null | undefined;
};

/** @internal */
export const ListIssuesOrdering$inboundSchema: z.ZodNativeEnum<
  typeof ListIssuesOrdering
> = z.nativeEnum(ListIssuesOrdering);

/** @internal */
export const ListIssuesOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListIssuesOrdering
> = ListIssuesOrdering$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIssuesOrdering$ {
  /** @deprecated use `ListIssuesOrdering$inboundSchema` instead. */
  export const inboundSchema = ListIssuesOrdering$inboundSchema;
  /** @deprecated use `ListIssuesOrdering$outboundSchema` instead. */
  export const outboundSchema = ListIssuesOrdering$outboundSchema;
}

/** @internal */
export const ListIssuesRequest$inboundSchema: z.ZodType<
  ListIssuesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  state: z.nullable(models.State$inboundSchema).optional(),
  ordering: z.nullable(ListIssuesOrdering$inboundSchema).optional(),
  page: z.number().int().default(1),
  page_size: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
  });
});

/** @internal */
export type ListIssuesRequest$Outbound = {
  state?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size?: number | null | undefined;
};

/** @internal */
export const ListIssuesRequest$outboundSchema: z.ZodType<
  ListIssuesRequest$Outbound,
  z.ZodTypeDef,
  ListIssuesRequest
> = z.object({
  state: z.nullable(models.State$outboundSchema).optional(),
  ordering: z.nullable(ListIssuesOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIssuesRequest$ {
  /** @deprecated use `ListIssuesRequest$inboundSchema` instead. */
  export const inboundSchema = ListIssuesRequest$inboundSchema;
  /** @deprecated use `ListIssuesRequest$outboundSchema` instead. */
  export const outboundSchema = ListIssuesRequest$outboundSchema;
  /** @deprecated use `ListIssuesRequest$Outbound` instead. */
  export type Outbound = ListIssuesRequest$Outbound;
}

export function listIssuesRequestToJSON(
  listIssuesRequest: ListIssuesRequest,
): string {
  return JSON.stringify(
    ListIssuesRequest$outboundSchema.parse(listIssuesRequest),
  );
}

export function listIssuesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListIssuesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListIssuesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIssuesRequest' from JSON`,
  );
}
