/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListSnapshotChaptersOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListSnapshotChaptersOrdering = ClosedEnum<
  typeof ListSnapshotChaptersOrdering
>;

export type ListSnapshotChaptersRequest = {
  snapshotId: string;
  /**
   * Ordering field
   */
  ordering?: ListSnapshotChaptersOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListSnapshotChaptersOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListSnapshotChaptersOrdering
> = z.nativeEnum(ListSnapshotChaptersOrdering);

/** @internal */
export type ListSnapshotChaptersRequest$Outbound = {
  snapshot_id: string;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListSnapshotChaptersRequest$outboundSchema: z.ZodType<
  ListSnapshotChaptersRequest$Outbound,
  z.ZodTypeDef,
  ListSnapshotChaptersRequest
> = z.object({
  snapshotId: z.string(),
  ordering: z.nullable(ListSnapshotChaptersOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    snapshotId: "snapshot_id",
    pageSize: "page_size",
  });
});

export function listSnapshotChaptersRequestToJSON(
  listSnapshotChaptersRequest: ListSnapshotChaptersRequest,
): string {
  return JSON.stringify(
    ListSnapshotChaptersRequest$outboundSchema.parse(
      listSnapshotChaptersRequest,
    ),
  );
}
