/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListSnapshotReleasesOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  PublishedAt: "published_at",
  MinusPublishedAt: "-published_at",
} as const;
/**
 * Ordering field
 */
export type ListSnapshotReleasesOrdering = ClosedEnum<
  typeof ListSnapshotReleasesOrdering
>;

export type ListSnapshotReleasesRequest = {
  snapshotId: string;
  /**
   * Ordering field
   */
  ordering?: ListSnapshotReleasesOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListSnapshotReleasesOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListSnapshotReleasesOrdering
> = z.nativeEnum(ListSnapshotReleasesOrdering);

/** @internal */
export type ListSnapshotReleasesRequest$Outbound = {
  snapshot_id: string;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListSnapshotReleasesRequest$outboundSchema: z.ZodType<
  ListSnapshotReleasesRequest$Outbound,
  z.ZodTypeDef,
  ListSnapshotReleasesRequest
> = z.object({
  snapshotId: z.string(),
  ordering: z.nullable(ListSnapshotReleasesOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    snapshotId: "snapshot_id",
    pageSize: "page_size",
  });
});

export function listSnapshotReleasesRequestToJSON(
  listSnapshotReleasesRequest: ListSnapshotReleasesRequest,
): string {
  return JSON.stringify(
    ListSnapshotReleasesRequest$outboundSchema.parse(
      listSnapshotReleasesRequest,
    ),
  );
}
