/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListMembersOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListMembersOrdering = ClosedEnum<typeof ListMembersOrdering>;

export type ListMembersRequest = {
  /**
   * Company of the user
   */
  company?: string | null | undefined;
  /**
   * Location of the member
   */
  location?: string | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListMembersOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListMembersOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListMembersOrdering
> = z.nativeEnum(ListMembersOrdering);

/** @internal */
export type ListMembersRequest$Outbound = {
  company?: string | null | undefined;
  location?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListMembersRequest$outboundSchema: z.ZodType<
  ListMembersRequest$Outbound,
  z.ZodTypeDef,
  ListMembersRequest
> = z.object({
  company: z.nullable(z.string()).optional(),
  location: z.nullable(z.string()).optional(),
  ordering: z.nullable(ListMembersOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listMembersRequestToJSON(
  listMembersRequest: ListMembersRequest,
): string {
  return JSON.stringify(
    ListMembersRequest$outboundSchema.parse(listMembersRequest),
  );
}
