/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Ordering field
 */
export const ListIssuesOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListIssuesOrdering = ClosedEnum<typeof ListIssuesOrdering>;

export type ListIssuesRequest = {
  /**
   * Organization that issues belong to (filtered by repository owner)
   */
  organization?: string | null | undefined;
  /**
   * Repository that issues belong to
   */
  repository?: string | null | undefined;
  /**
   * Issue state
   */
  state?: models.State | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListIssuesOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListIssuesOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListIssuesOrdering
> = z.nativeEnum(ListIssuesOrdering);

/** @internal */
export type ListIssuesRequest$Outbound = {
  organization?: string | null | undefined;
  repository?: string | null | undefined;
  state?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListIssuesRequest$outboundSchema: z.ZodType<
  ListIssuesRequest$Outbound,
  z.ZodTypeDef,
  ListIssuesRequest
> = z.object({
  organization: z.nullable(z.string()).optional(),
  repository: z.nullable(z.string()).optional(),
  state: z.nullable(models.State$outboundSchema).optional(),
  ordering: z.nullable(ListIssuesOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listIssuesRequestToJSON(
  listIssuesRequest: ListIssuesRequest,
): string {
  return JSON.stringify(
    ListIssuesRequest$outboundSchema.parse(listIssuesRequest),
  );
}
