/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListSnapshotsOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
  StartAt: "start_at",
  MinusStartAt: "-start_at",
} as const;
/**
 * Ordering field
 */
export type ListSnapshotsOrdering = ClosedEnum<typeof ListSnapshotsOrdering>;

export type ListSnapshotsRequest = {
  /**
   * Ordering field
   */
  ordering?: ListSnapshotsOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListSnapshotsOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListSnapshotsOrdering
> = z.nativeEnum(ListSnapshotsOrdering);

/** @internal */
export type ListSnapshotsRequest$Outbound = {
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListSnapshotsRequest$outboundSchema: z.ZodType<
  ListSnapshotsRequest$Outbound,
  z.ZodTypeDef,
  ListSnapshotsRequest
> = z.object({
  ordering: z.nullable(ListSnapshotsOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listSnapshotsRequestToJSON(
  listSnapshotsRequest: ListSnapshotsRequest,
): string {
  return JSON.stringify(
    ListSnapshotsRequest$outboundSchema.parse(listSnapshotsRequest),
  );
}
