/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Ordering field
 */
export const ListProjectsOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListProjectsOrdering = ClosedEnum<typeof ListProjectsOrdering>;

export type ListProjectsRequest = {
  /**
   * Level of the project
   */
  level?: models.ProjectLevel | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListProjectsOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListProjectsOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListProjectsOrdering
> = z.nativeEnum(ListProjectsOrdering);

/** @internal */
export type ListProjectsRequest$Outbound = {
  level?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListProjectsRequest$outboundSchema: z.ZodType<
  ListProjectsRequest$Outbound,
  z.ZodTypeDef,
  ListProjectsRequest
> = z.object({
  level: z.nullable(models.ProjectLevel$outboundSchema).optional(),
  ordering: z.nullable(ListProjectsOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listProjectsRequestToJSON(
  listProjectsRequest: ListProjectsRequest,
): string {
  return JSON.stringify(
    ListProjectsRequest$outboundSchema.parse(listProjectsRequest),
  );
}
