/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListEventsOrdering = {
  StartDate: "start_date",
  MinusStartDate: "-start_date",
  EndDate: "end_date",
  MinusEndDate: "-end_date",
} as const;
/**
 * Ordering field
 */
export type ListEventsOrdering = ClosedEnum<typeof ListEventsOrdering>;

export type ListEventsRequest = {
  /**
   * Ordering field
   */
  ordering?: ListEventsOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListEventsOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListEventsOrdering
> = z.nativeEnum(ListEventsOrdering);

/** @internal */
export type ListEventsRequest$Outbound = {
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListEventsRequest$outboundSchema: z.ZodType<
  ListEventsRequest$Outbound,
  z.ZodTypeDef,
  ListEventsRequest
> = z.object({
  ordering: z.nullable(ListEventsOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listEventsRequestToJSON(
  listEventsRequest: ListEventsRequest,
): string {
  return JSON.stringify(
    ListEventsRequest$outboundSchema.parse(listEventsRequest),
  );
}
