/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

export const ListMilestonesOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
export type ListMilestonesOrdering = ClosedEnum<typeof ListMilestonesOrdering>;

export type ListMilestonesRequest = {
  /**
   * Organization that milestones belong to (filtered by repository owner)
   */
  organization?: string | null | undefined;
  /**
   * Repository that milestones belong to
   */
  repository?: string | null | undefined;
  /**
   * Milestone state
   */
  state?: models.State | null | undefined;
  ordering?: ListMilestonesOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListMilestonesOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListMilestonesOrdering
> = z.nativeEnum(ListMilestonesOrdering);

/** @internal */
export type ListMilestonesRequest$Outbound = {
  organization?: string | null | undefined;
  repository?: string | null | undefined;
  state?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListMilestonesRequest$outboundSchema: z.ZodType<
  ListMilestonesRequest$Outbound,
  z.ZodTypeDef,
  ListMilestonesRequest
> = z.object({
  organization: z.nullable(z.string()).optional(),
  repository: z.nullable(z.string()).optional(),
  state: z.nullable(models.State$outboundSchema).optional(),
  ordering: z.nullable(ListMilestonesOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listMilestonesRequestToJSON(
  listMilestonesRequest: ListMilestonesRequest,
): string {
  return JSON.stringify(
    ListMilestonesRequest$outboundSchema.parse(listMilestonesRequest),
  );
}
