/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListChaptersOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListChaptersOrdering = ClosedEnum<typeof ListChaptersOrdering>;

export type ListChaptersRequest = {
  /**
   * Country of the chapter
   */
  country?: string | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListChaptersOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListChaptersOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListChaptersOrdering
> = z.nativeEnum(ListChaptersOrdering);

/** @internal */
export type ListChaptersRequest$Outbound = {
  country?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListChaptersRequest$outboundSchema: z.ZodType<
  ListChaptersRequest$Outbound,
  z.ZodTypeDef,
  ListChaptersRequest
> = z.object({
  country: z.nullable(z.string()).optional(),
  ordering: z.nullable(ListChaptersOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listChaptersRequestToJSON(
  listChaptersRequest: ListChaptersRequest,
): string {
  return JSON.stringify(
    ListChaptersRequest$outboundSchema.parse(listChaptersRequest),
  );
}
