/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Ordering field
 */
export const ListSponsorsOrdering = {
  Name: "name",
  MinusName: "-name",
} as const;
/**
 * Ordering field
 */
export type ListSponsorsOrdering = ClosedEnum<typeof ListSponsorsOrdering>;

export type ListSponsorsRequest = {
  /**
   * Member status of the sponsor
   */
  isMember?: boolean | null | undefined;
  /**
   * Member type of the sponsor
   */
  memberType?: models.MemberType | null | undefined;
  /**
   * Filter by the type of sponsorship (e.g., Gold, Silver, Platinum).
   */
  sponsorType?: string | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListSponsorsOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListSponsorsOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListSponsorsOrdering
> = z.nativeEnum(ListSponsorsOrdering);

/** @internal */
export type ListSponsorsRequest$Outbound = {
  is_member?: boolean | null | undefined;
  member_type?: string | null | undefined;
  sponsor_type?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListSponsorsRequest$outboundSchema: z.ZodType<
  ListSponsorsRequest$Outbound,
  z.ZodTypeDef,
  ListSponsorsRequest
> = z.object({
  isMember: z.nullable(z.boolean()).optional(),
  memberType: z.nullable(models.MemberType$outboundSchema).optional(),
  sponsorType: z.nullable(z.string()).optional(),
  ordering: z.nullable(ListSponsorsOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    isMember: "is_member",
    memberType: "member_type",
    sponsorType: "sponsor_type",
    pageSize: "page_size",
  });
});

export function listSponsorsRequestToJSON(
  listSponsorsRequest: ListSponsorsRequest,
): string {
  return JSON.stringify(
    ListSponsorsRequest$outboundSchema.parse(listSponsorsRequest),
  );
}
