/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListReleasesOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  PublishedAt: "published_at",
  MinusPublishedAt: "-published_at",
} as const;
/**
 * Ordering field
 */
export type ListReleasesOrdering = ClosedEnum<typeof ListReleasesOrdering>;

export type ListReleasesRequest = {
  /**
   * Organization that releases belong to (filtered by repository owner)
   */
  organization?: string | null | undefined;
  /**
   * Repository that releases belong to
   */
  repository?: string | null | undefined;
  /**
   * Tag name of the release
   */
  tagName?: string | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListReleasesOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListReleasesOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListReleasesOrdering
> = z.nativeEnum(ListReleasesOrdering);

/** @internal */
export type ListReleasesRequest$Outbound = {
  organization?: string | null | undefined;
  repository?: string | null | undefined;
  tag_name?: string | null | undefined;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListReleasesRequest$outboundSchema: z.ZodType<
  ListReleasesRequest$Outbound,
  z.ZodTypeDef,
  ListReleasesRequest
> = z.object({
  organization: z.nullable(z.string()).optional(),
  repository: z.nullable(z.string()).optional(),
  tagName: z.nullable(z.string()).optional(),
  ordering: z.nullable(ListReleasesOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    tagName: "tag_name",
    pageSize: "page_size",
  });
});

export function listReleasesRequestToJSON(
  listReleasesRequest: ListReleasesRequest,
): string {
  return JSON.stringify(
    ListReleasesRequest$outboundSchema.parse(listReleasesRequest),
  );
}
