/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListSnapshotIssuesOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListSnapshotIssuesOrdering = ClosedEnum<
  typeof ListSnapshotIssuesOrdering
>;

export type ListSnapshotIssuesRequest = {
  snapshotId: string;
  /**
   * Ordering field
   */
  ordering?: ListSnapshotIssuesOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListSnapshotIssuesOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListSnapshotIssuesOrdering
> = z.nativeEnum(ListSnapshotIssuesOrdering);

/** @internal */
export type ListSnapshotIssuesRequest$Outbound = {
  snapshot_id: string;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListSnapshotIssuesRequest$outboundSchema: z.ZodType<
  ListSnapshotIssuesRequest$Outbound,
  z.ZodTypeDef,
  ListSnapshotIssuesRequest
> = z.object({
  snapshotId: z.string(),
  ordering: z.nullable(ListSnapshotIssuesOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    snapshotId: "snapshot_id",
    pageSize: "page_size",
  });
});

export function listSnapshotIssuesRequestToJSON(
  listSnapshotIssuesRequest: ListSnapshotIssuesRequest,
): string {
  return JSON.stringify(
    ListSnapshotIssuesRequest$outboundSchema.parse(listSnapshotIssuesRequest),
  );
}
