/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListSnapshotProjectsOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListSnapshotProjectsOrdering = ClosedEnum<
  typeof ListSnapshotProjectsOrdering
>;

export type ListSnapshotProjectsRequest = {
  snapshotId: string;
  /**
   * Ordering field
   */
  ordering?: ListSnapshotProjectsOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListSnapshotProjectsOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListSnapshotProjectsOrdering
> = z.nativeEnum(ListSnapshotProjectsOrdering);

/** @internal */
export type ListSnapshotProjectsRequest$Outbound = {
  snapshot_id: string;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListSnapshotProjectsRequest$outboundSchema: z.ZodType<
  ListSnapshotProjectsRequest$Outbound,
  z.ZodTypeDef,
  ListSnapshotProjectsRequest
> = z.object({
  snapshotId: z.string(),
  ordering: z.nullable(ListSnapshotProjectsOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    snapshotId: "snapshot_id",
    pageSize: "page_size",
  });
});

export function listSnapshotProjectsRequestToJSON(
  listSnapshotProjectsRequest: ListSnapshotProjectsRequest,
): string {
  return JSON.stringify(
    ListSnapshotProjectsRequest$outboundSchema.parse(
      listSnapshotProjectsRequest,
    ),
  );
}
