/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListCommitteesOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListCommitteesOrdering = ClosedEnum<typeof ListCommitteesOrdering>;

export type ListCommitteesRequest = {
  /**
   * Ordering field
   */
  ordering?: ListCommitteesOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListCommitteesOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListCommitteesOrdering
> = z.nativeEnum(ListCommitteesOrdering);

/** @internal */
export type ListCommitteesRequest$Outbound = {
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListCommitteesRequest$outboundSchema: z.ZodType<
  ListCommitteesRequest$Outbound,
  z.ZodTypeDef,
  ListCommitteesRequest
> = z.object({
  ordering: z.nullable(ListCommitteesOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
  });
});

export function listCommitteesRequestToJSON(
  listCommitteesRequest: ListCommitteesRequest,
): string {
  return JSON.stringify(
    ListCommitteesRequest$outboundSchema.parse(listCommitteesRequest),
  );
}
