/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListSnapshotMembersOrdering = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  UpdatedAt: "updated_at",
  MinusUpdatedAt: "-updated_at",
} as const;
/**
 * Ordering field
 */
export type ListSnapshotMembersOrdering = ClosedEnum<
  typeof ListSnapshotMembersOrdering
>;

export type ListSnapshotMembersRequest = {
  snapshotId: string;
  /**
   * Ordering field
   */
  ordering?: ListSnapshotMembersOrdering | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListSnapshotMembersOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListSnapshotMembersOrdering
> = z.nativeEnum(ListSnapshotMembersOrdering);

/** @internal */
export type ListSnapshotMembersRequest$Outbound = {
  snapshot_id: string;
  ordering?: string | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListSnapshotMembersRequest$outboundSchema: z.ZodType<
  ListSnapshotMembersRequest$Outbound,
  z.ZodTypeDef,
  ListSnapshotMembersRequest
> = z.object({
  snapshotId: z.string(),
  ordering: z.nullable(ListSnapshotMembersOrdering$outboundSchema).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    snapshotId: "snapshot_id",
    pageSize: "page_size",
  });
});

export function listSnapshotMembersRequestToJSON(
  listSnapshotMembersRequest: ListSnapshotMembersRequest,
): string {
  return JSON.stringify(
    ListSnapshotMembersRequest$outboundSchema.parse(listSnapshotMembersRequest),
  );
}
