/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Ordering field
 */
export const ListEventsOrdering = {
  StartDate: "start_date",
  MinusStartDate: "-start_date",
  EndDate: "end_date",
  MinusEndDate: "-end_date",
  Latitude: "latitude",
  MinusLatitude: "-latitude",
  Longitude: "longitude",
  MinusLongitude: "-longitude",
} as const;
/**
 * Ordering field
 */
export type ListEventsOrdering = ClosedEnum<typeof ListEventsOrdering>;

export type ListEventsRequest = {
  /**
   * Latitude greater than or equal to
   */
  latitudeGte?: number | null | undefined;
  /**
   * Latitude less than or equal to
   */
  latitudeLte?: number | null | undefined;
  /**
   * Longitude greater than or equal to
   */
  longitudeGte?: number | null | undefined;
  /**
   * Longitude less than or equal to
   */
  longitudeLte?: number | null | undefined;
  /**
   * Ordering field
   */
  ordering?: ListEventsOrdering | null | undefined;
  /**
   * Filter for upcoming events
   */
  isUpcoming?: boolean | null | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
  /**
   * Number of items per page
   */
  pageSize?: number | undefined;
};

/** @internal */
export const ListEventsOrdering$outboundSchema: z.ZodNativeEnum<
  typeof ListEventsOrdering
> = z.nativeEnum(ListEventsOrdering);

/** @internal */
export type ListEventsRequest$Outbound = {
  latitude_gte?: number | null | undefined;
  latitude_lte?: number | null | undefined;
  longitude_gte?: number | null | undefined;
  longitude_lte?: number | null | undefined;
  ordering?: string | null | undefined;
  is_upcoming?: boolean | null | undefined;
  page: number;
  page_size: number;
};

/** @internal */
export const ListEventsRequest$outboundSchema: z.ZodType<
  ListEventsRequest$Outbound,
  z.ZodTypeDef,
  ListEventsRequest
> = z.object({
  latitudeGte: z.nullable(z.number()).optional(),
  latitudeLte: z.nullable(z.number()).optional(),
  longitudeGte: z.nullable(z.number()).optional(),
  longitudeLte: z.nullable(z.number()).optional(),
  ordering: z.nullable(ListEventsOrdering$outboundSchema).optional(),
  isUpcoming: z.nullable(z.boolean()).optional(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
}).transform((v) => {
  return remap$(v, {
    latitudeGte: "latitude_gte",
    latitudeLte: "latitude_lte",
    longitudeGte: "longitude_gte",
    longitudeLte: "longitude_lte",
    isUpcoming: "is_upcoming",
    pageSize: "page_size",
  });
});

export function listEventsRequestToJSON(
  listEventsRequest: ListEventsRequest,
): string {
  return JSON.stringify(
    ListEventsRequest$outboundSchema.parse(listEventsRequest),
  );
}
