/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Event category.
 */
export const Category = {
  AppsecDays: "appsec_days",
  Global: "global",
  Other: "other",
  Partner: "partner",
} as const;
/**
 * Event category.
 */
export type Category = ClosedEnum<typeof Category>;

/** @internal */
export const Category$outboundSchema: z.ZodNativeEnum<typeof Category> = z
  .nativeEnum(Category);
