/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Chapter (minimal fields for list display).
 */
export type Chapter = {
  createdAt: Date;
  key: string;
  name: string;
  updatedAt: Date;
};

/** @internal */
export const Chapter$inboundSchema: z.ZodType<Chapter, z.ZodTypeDef, unknown> =
  z.object({
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    key: z.string(),
    name: z.string(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });

export function chapterFromJSON(
  jsonString: string,
): SafeParseResult<Chapter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Chapter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Chapter' from JSON`,
  );
}
