/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Chapter.
 */
export type ChapterSchema = {
  country: string;
  createdAt: Date;
  name: string;
  region: string;
  updatedAt: Date;
};

/** @internal */
export const ChapterSchema$inboundSchema: z.ZodType<
  ChapterSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  country: z.string(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  name: z.string(),
  region: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type ChapterSchema$Outbound = {
  country: string;
  created_at: string;
  name: string;
  region: string;
  updated_at: string;
};

/** @internal */
export const ChapterSchema$outboundSchema: z.ZodType<
  ChapterSchema$Outbound,
  z.ZodTypeDef,
  ChapterSchema
> = z.object({
  country: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  name: z.string(),
  region: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChapterSchema$ {
  /** @deprecated use `ChapterSchema$inboundSchema` instead. */
  export const inboundSchema = ChapterSchema$inboundSchema;
  /** @deprecated use `ChapterSchema$outboundSchema` instead. */
  export const outboundSchema = ChapterSchema$outboundSchema;
  /** @deprecated use `ChapterSchema$Outbound` instead. */
  export type Outbound = ChapterSchema$Outbound;
}

export function chapterSchemaToJSON(chapterSchema: ChapterSchema): string {
  return JSON.stringify(ChapterSchema$outboundSchema.parse(chapterSchema));
}

export function chapterSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ChapterSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChapterSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChapterSchema' from JSON`,
  );
}
