/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Chapter (used in single item endpoints).
 */
export type ChapterDetail = {
  createdAt: Date;
  key: string;
  latitude?: number | null | undefined;
  longitude?: number | null | undefined;
  name: string;
  updatedAt: Date;
  country: string;
  region: string;
};

/** @internal */
export const ChapterDetail$inboundSchema: z.ZodType<
  ChapterDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  key: z.string(),
  latitude: z.nullable(z.number()).optional(),
  longitude: z.nullable(z.number()).optional(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  country: z.string(),
  region: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function chapterDetailFromJSON(
  jsonString: string,
): SafeParseResult<ChapterDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChapterDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChapterDetail' from JSON`,
  );
}
