/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Chapter (minimal fields for list display).
 */
export type Chapter = {
  createdAt: Date;
  key: string;
  name: string;
  updatedAt: Date;
};

/** @internal */
export const Chapter$inboundSchema: z.ZodType<Chapter, z.ZodTypeDef, unknown> =
  z.object({
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    key: z.string(),
    name: z.string(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });

/** @internal */
export type Chapter$Outbound = {
  created_at: string;
  key: string;
  name: string;
  updated_at: string;
};

/** @internal */
export const Chapter$outboundSchema: z.ZodType<
  Chapter$Outbound,
  z.ZodTypeDef,
  Chapter
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  key: z.string(),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Chapter$ {
  /** @deprecated use `Chapter$inboundSchema` instead. */
  export const inboundSchema = Chapter$inboundSchema;
  /** @deprecated use `Chapter$outboundSchema` instead. */
  export const outboundSchema = Chapter$outboundSchema;
  /** @deprecated use `Chapter$Outbound` instead. */
  export type Outbound = Chapter$Outbound;
}

export function chapterToJSON(chapter: Chapter): string {
  return JSON.stringify(Chapter$outboundSchema.parse(chapter));
}

export function chapterFromJSON(
  jsonString: string,
): SafeParseResult<Chapter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Chapter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Chapter' from JSON`,
  );
}
