/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Chapter (used in single item endpoints).
 */
export type ChapterDetail = {
  createdAt: Date;
  key: string;
  name: string;
  updatedAt: Date;
  country: string;
  region: string;
};

/** @internal */
export const ChapterDetail$inboundSchema: z.ZodType<
  ChapterDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  key: z.string(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  country: z.string(),
  region: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type ChapterDetail$Outbound = {
  created_at: string;
  key: string;
  name: string;
  updated_at: string;
  country: string;
  region: string;
};

/** @internal */
export const ChapterDetail$outboundSchema: z.ZodType<
  ChapterDetail$Outbound,
  z.ZodTypeDef,
  ChapterDetail
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  key: z.string(),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
  country: z.string(),
  region: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChapterDetail$ {
  /** @deprecated use `ChapterDetail$inboundSchema` instead. */
  export const inboundSchema = ChapterDetail$inboundSchema;
  /** @deprecated use `ChapterDetail$outboundSchema` instead. */
  export const outboundSchema = ChapterDetail$outboundSchema;
  /** @deprecated use `ChapterDetail$Outbound` instead. */
  export type Outbound = ChapterDetail$Outbound;
}

export function chapterDetailToJSON(chapterDetail: ChapterDetail): string {
  return JSON.stringify(ChapterDetail$outboundSchema.parse(chapterDetail));
}

export function chapterDetailFromJSON(
  jsonString: string,
): SafeParseResult<ChapterDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChapterDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChapterDetail' from JSON`,
  );
}
