/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Committee (used in single item endpoints).
 */
export type CommitteeDetail = {
  createdAt: Date;
  key: string;
  name: string;
  updatedAt: Date;
  description: string;
};

/** @internal */
export const CommitteeDetail$inboundSchema: z.ZodType<
  CommitteeDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  key: z.string(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function committeeDetailFromJSON(
  jsonString: string,
): SafeParseResult<CommitteeDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommitteeDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommitteeDetail' from JSON`,
  );
}
