/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Committee (minimal fields for list display).
 */
export type Committee = {
  createdAt: Date;
  key: string;
  name: string;
  updatedAt: Date;
};

/** @internal */
export const Committee$inboundSchema: z.ZodType<
  Committee,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  key: z.string(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type Committee$Outbound = {
  created_at: string;
  key: string;
  name: string;
  updated_at: string;
};

/** @internal */
export const Committee$outboundSchema: z.ZodType<
  Committee$Outbound,
  z.ZodTypeDef,
  Committee
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  key: z.string(),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Committee$ {
  /** @deprecated use `Committee$inboundSchema` instead. */
  export const inboundSchema = Committee$inboundSchema;
  /** @deprecated use `Committee$outboundSchema` instead. */
  export const outboundSchema = Committee$outboundSchema;
  /** @deprecated use `Committee$Outbound` instead. */
  export type Outbound = Committee$Outbound;
}

export function committeeToJSON(committee: Committee): string {
  return JSON.stringify(Committee$outboundSchema.parse(committee));
}

export function committeeFromJSON(
  jsonString: string,
): SafeParseResult<Committee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Committee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Committee' from JSON`,
  );
}
