/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Event (used in single item endpoints).
 */
export type EventDetail = {
  endDate?: Date | null | undefined;
  key: string;
  name: string;
  startDate: Date;
  url?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const EventDetail$inboundSchema: z.ZodType<
  EventDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  end_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  key: z.string(),
  name: z.string(),
  start_date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "end_date": "endDate",
    "start_date": "startDate",
  });
});

/** @internal */
export type EventDetail$Outbound = {
  end_date?: string | null | undefined;
  key: string;
  name: string;
  start_date: string;
  url?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const EventDetail$outboundSchema: z.ZodType<
  EventDetail$Outbound,
  z.ZodTypeDef,
  EventDetail
> = z.object({
  endDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  key: z.string(),
  name: z.string(),
  startDate: z.date().transform(v => v.toISOString()),
  url: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    endDate: "end_date",
    startDate: "start_date",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EventDetail$ {
  /** @deprecated use `EventDetail$inboundSchema` instead. */
  export const inboundSchema = EventDetail$inboundSchema;
  /** @deprecated use `EventDetail$outboundSchema` instead. */
  export const outboundSchema = EventDetail$outboundSchema;
  /** @deprecated use `EventDetail$Outbound` instead. */
  export type Outbound = EventDetail$Outbound;
}

export function eventDetailToJSON(eventDetail: EventDetail): string {
  return JSON.stringify(EventDetail$outboundSchema.parse(eventDetail));
}

export function eventDetailFromJSON(
  jsonString: string,
): SafeParseResult<EventDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventDetail' from JSON`,
  );
}
