/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Event (minimal fields for list display).
 */
export type Event = {
  endDate?: Date | null | undefined;
  key: string;
  latitude?: number | null | undefined;
  longitude?: number | null | undefined;
  name: string;
  startDate: Date;
  url?: string | null | undefined;
};

/** @internal */
export const Event$inboundSchema: z.ZodType<Event, z.ZodTypeDef, unknown> = z
  .object({
    end_date: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    key: z.string(),
    latitude: z.nullable(z.number()).optional(),
    longitude: z.nullable(z.number()).optional(),
    name: z.string(),
    start_date: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    url: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "end_date": "endDate",
      "start_date": "startDate",
    });
  });

export function eventFromJSON(
  jsonString: string,
): SafeParseResult<Event, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Event$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Event' from JSON`,
  );
}
