/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Event (used in single item endpoints).
 */
export type EventDetail = {
  endDate?: Date | null | undefined;
  key: string;
  name: string;
  startDate: Date;
  url?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const EventDetail$inboundSchema: z.ZodType<
  EventDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  end_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  key: z.string(),
  name: z.string(),
  start_date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "end_date": "endDate",
    "start_date": "startDate",
  });
});

export function eventDetailFromJSON(
  jsonString: string,
): SafeParseResult<EventDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventDetail' from JSON`,
  );
}
