/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { State, State$inboundSchema } from "./state.js";

/**
 * Detail schema for Issue (used in single item endpoints).
 */
export type IssueDetail = {
  createdAt: Date;
  state: State;
  title: string;
  updatedAt: Date;
  url: string;
  body: string;
};

/** @internal */
export const IssueDetail$inboundSchema: z.ZodType<
  IssueDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  state: State$inboundSchema,
  title: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.string(),
  body: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function issueDetailFromJSON(
  jsonString: string,
): SafeParseResult<IssueDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IssueDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IssueDetail' from JSON`,
  );
}
