/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Issue state choices.
 */
export const IssueState = {
  Open: "open",
  Closed: "closed",
} as const;
/**
 * Issue state choices.
 */
export type IssueState = ClosedEnum<typeof IssueState>;

/** @internal */
export const IssueState$inboundSchema: z.ZodNativeEnum<typeof IssueState> = z
  .nativeEnum(IssueState);
/** @internal */
export const IssueState$outboundSchema: z.ZodNativeEnum<typeof IssueState> =
  IssueState$inboundSchema;
