/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { State, State$inboundSchema, State$outboundSchema } from "./state.js";

/**
 * Schema for Issue.
 */
export type IssueSchema = {
  body: string;
  createdAt: Date;
  title: string;
  state: State;
  updatedAt: Date;
  url: string;
};

/** @internal */
export const IssueSchema$inboundSchema: z.ZodType<
  IssueSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  title: z.string(),
  state: State$inboundSchema,
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type IssueSchema$Outbound = {
  body: string;
  created_at: string;
  title: string;
  state: string;
  updated_at: string;
  url: string;
};

/** @internal */
export const IssueSchema$outboundSchema: z.ZodType<
  IssueSchema$Outbound,
  z.ZodTypeDef,
  IssueSchema
> = z.object({
  body: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  title: z.string(),
  state: State$outboundSchema,
  updatedAt: z.date().transform(v => v.toISOString()),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IssueSchema$ {
  /** @deprecated use `IssueSchema$inboundSchema` instead. */
  export const inboundSchema = IssueSchema$inboundSchema;
  /** @deprecated use `IssueSchema$outboundSchema` instead. */
  export const outboundSchema = IssueSchema$outboundSchema;
  /** @deprecated use `IssueSchema$Outbound` instead. */
  export type Outbound = IssueSchema$Outbound;
}

export function issueSchemaToJSON(issueSchema: IssueSchema): string {
  return JSON.stringify(IssueSchema$outboundSchema.parse(issueSchema));
}

export function issueSchemaFromJSON(
  jsonString: string,
): SafeParseResult<IssueSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IssueSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IssueSchema' from JSON`,
  );
}
