/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Leader.
 */
export type Leader = {
  key?: string | null | undefined;
  name: string;
};

/** @internal */
export const Leader$inboundSchema: z.ZodType<Leader, z.ZodTypeDef, unknown> = z
  .object({
    key: z.nullable(z.string()).optional(),
    name: z.string(),
  });

export function leaderFromJSON(
  jsonString: string,
): SafeParseResult<Leader, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Leader$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Leader' from JSON`,
  );
}
