/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Member (minimal fields for list display).
 */
export type Member = {
  avatarUrl: string;
  createdAt: Date;
  login: string;
  name: string;
  updatedAt: Date;
  url: string;
};

/** @internal */
export const Member$inboundSchema: z.ZodType<Member, z.ZodTypeDef, unknown> = z
  .object({
    avatar_url: z.string(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    login: z.string(),
    name: z.string(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    url: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "avatar_url": "avatarUrl",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });

export function memberFromJSON(
  jsonString: string,
): SafeParseResult<Member, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Member$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Member' from JSON`,
  );
}
