/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Member.
 */
export type MemberSchema = {
  avatarUrl: string;
  bio: string;
  company: string;
  createdAt: Date;
  email: string;
  followersCount: number;
  followingCount: number;
  location: string;
  login: string;
  name: string;
  publicRepositoriesCount: number;
  title: string;
  twitterUsername: string;
  updatedAt: Date;
  url: string;
};

/** @internal */
export const MemberSchema$inboundSchema: z.ZodType<
  MemberSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  avatar_url: z.string(),
  bio: z.string(),
  company: z.string(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  email: z.string(),
  followers_count: z.number().int(),
  following_count: z.number().int(),
  location: z.string(),
  login: z.string(),
  name: z.string(),
  public_repositories_count: z.number().int(),
  title: z.string(),
  twitter_username: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "avatar_url": "avatarUrl",
    "created_at": "createdAt",
    "followers_count": "followersCount",
    "following_count": "followingCount",
    "public_repositories_count": "publicRepositoriesCount",
    "twitter_username": "twitterUsername",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type MemberSchema$Outbound = {
  avatar_url: string;
  bio: string;
  company: string;
  created_at: string;
  email: string;
  followers_count: number;
  following_count: number;
  location: string;
  login: string;
  name: string;
  public_repositories_count: number;
  title: string;
  twitter_username: string;
  updated_at: string;
  url: string;
};

/** @internal */
export const MemberSchema$outboundSchema: z.ZodType<
  MemberSchema$Outbound,
  z.ZodTypeDef,
  MemberSchema
> = z.object({
  avatarUrl: z.string(),
  bio: z.string(),
  company: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  email: z.string(),
  followersCount: z.number().int(),
  followingCount: z.number().int(),
  location: z.string(),
  login: z.string(),
  name: z.string(),
  publicRepositoriesCount: z.number().int(),
  title: z.string(),
  twitterUsername: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    avatarUrl: "avatar_url",
    createdAt: "created_at",
    followersCount: "followers_count",
    followingCount: "following_count",
    publicRepositoriesCount: "public_repositories_count",
    twitterUsername: "twitter_username",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MemberSchema$ {
  /** @deprecated use `MemberSchema$inboundSchema` instead. */
  export const inboundSchema = MemberSchema$inboundSchema;
  /** @deprecated use `MemberSchema$outboundSchema` instead. */
  export const outboundSchema = MemberSchema$outboundSchema;
  /** @deprecated use `MemberSchema$Outbound` instead. */
  export type Outbound = MemberSchema$Outbound;
}

export function memberSchemaToJSON(memberSchema: MemberSchema): string {
  return JSON.stringify(MemberSchema$outboundSchema.parse(memberSchema));
}

export function memberSchemaFromJSON(
  jsonString: string,
): SafeParseResult<MemberSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MemberSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MemberSchema' from JSON`,
  );
}
