/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const MemberType = {
  Platinum: "Platinum",
  Gold: "Gold",
  Silver: "Silver",
} as const;
export type MemberType = ClosedEnum<typeof MemberType>;

/** @internal */
export const MemberType$inboundSchema: z.ZodNativeEnum<typeof MemberType> = z
  .nativeEnum(MemberType);

/** @internal */
export const MemberType$outboundSchema: z.ZodNativeEnum<typeof MemberType> =
  MemberType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MemberType$ {
  /** @deprecated use `MemberType$inboundSchema` instead. */
  export const inboundSchema = MemberType$inboundSchema;
  /** @deprecated use `MemberType$outboundSchema` instead. */
  export const outboundSchema = MemberType$outboundSchema;
}
