/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { State, State$inboundSchema } from "./state.js";

/**
 * Detail schema for Milestone (used in single item endpoints).
 */
export type MilestoneDetail = {
  createdAt: Date;
  number: number;
  state: State;
  title: string;
  updatedAt: Date;
  url: string;
  body: string;
  closedIssuesCount: number;
  dueOn: Date | null;
  openIssuesCount: number;
};

/** @internal */
export const MilestoneDetail$inboundSchema: z.ZodType<
  MilestoneDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  number: z.number().int(),
  state: State$inboundSchema,
  title: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.string(),
  body: z.string(),
  closed_issues_count: z.number().int(),
  due_on: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  open_issues_count: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "closed_issues_count": "closedIssuesCount",
    "due_on": "dueOn",
    "open_issues_count": "openIssuesCount",
  });
});

export function milestoneDetailFromJSON(
  jsonString: string,
): SafeParseResult<MilestoneDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MilestoneDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MilestoneDetail' from JSON`,
  );
}
