/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { State, State$inboundSchema } from "./state.js";

/**
 * Schema for Milestone (minimal fields for list display).
 */
export type Milestone = {
  createdAt: Date;
  number: number;
  state: State;
  title: string;
  updatedAt: Date;
  url: string;
};

/** @internal */
export const Milestone$inboundSchema: z.ZodType<
  Milestone,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  number: z.number().int(),
  state: State$inboundSchema,
  title: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function milestoneFromJSON(
  jsonString: string,
): SafeParseResult<Milestone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Milestone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Milestone' from JSON`,
  );
}
