/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Organization (used in single item endpoints).
 */
export type OrganizationDetail = {
  createdAt: Date;
  login: string;
  name: string;
  updatedAt: Date;
  company: string;
  location: string;
};

/** @internal */
export const OrganizationDetail$inboundSchema: z.ZodType<
  OrganizationDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  login: z.string(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  company: z.string(),
  location: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function organizationDetailFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationDetail' from JSON`,
  );
}
