/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Organization (used in single item endpoints).
 */
export type OrganizationDetail = {
  createdAt: Date;
  login: string;
  name: string;
  updatedAt: Date;
  company: string;
  location: string;
};

/** @internal */
export const OrganizationDetail$inboundSchema: z.ZodType<
  OrganizationDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  login: z.string(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  company: z.string(),
  location: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type OrganizationDetail$Outbound = {
  created_at: string;
  login: string;
  name: string;
  updated_at: string;
  company: string;
  location: string;
};

/** @internal */
export const OrganizationDetail$outboundSchema: z.ZodType<
  OrganizationDetail$Outbound,
  z.ZodTypeDef,
  OrganizationDetail
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  login: z.string(),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
  company: z.string(),
  location: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationDetail$ {
  /** @deprecated use `OrganizationDetail$inboundSchema` instead. */
  export const inboundSchema = OrganizationDetail$inboundSchema;
  /** @deprecated use `OrganizationDetail$outboundSchema` instead. */
  export const outboundSchema = OrganizationDetail$outboundSchema;
  /** @deprecated use `OrganizationDetail$Outbound` instead. */
  export type Outbound = OrganizationDetail$Outbound;
}

export function organizationDetailToJSON(
  organizationDetail: OrganizationDetail,
): string {
  return JSON.stringify(
    OrganizationDetail$outboundSchema.parse(organizationDetail),
  );
}

export function organizationDetailFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationDetail' from JSON`,
  );
}
