/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Organization.
 */
export type OrganizationSchema = {
  company: string;
  createdAt: Date;
  location: string;
  login: string;
  name: string;
  updatedAt: Date;
};

/** @internal */
export const OrganizationSchema$inboundSchema: z.ZodType<
  OrganizationSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  company: z.string(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  location: z.string(),
  login: z.string(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type OrganizationSchema$Outbound = {
  company: string;
  created_at: string;
  location: string;
  login: string;
  name: string;
  updated_at: string;
};

/** @internal */
export const OrganizationSchema$outboundSchema: z.ZodType<
  OrganizationSchema$Outbound,
  z.ZodTypeDef,
  OrganizationSchema
> = z.object({
  company: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  location: z.string(),
  login: z.string(),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationSchema$ {
  /** @deprecated use `OrganizationSchema$inboundSchema` instead. */
  export const inboundSchema = OrganizationSchema$inboundSchema;
  /** @deprecated use `OrganizationSchema$outboundSchema` instead. */
  export const outboundSchema = OrganizationSchema$outboundSchema;
  /** @deprecated use `OrganizationSchema$Outbound` instead. */
  export type Outbound = OrganizationSchema$Outbound;
}

export function organizationSchemaToJSON(
  organizationSchema: OrganizationSchema,
): string {
  return JSON.stringify(
    OrganizationSchema$outboundSchema.parse(organizationSchema),
  );
}

export function organizationSchemaFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationSchema' from JSON`,
  );
}
