/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Member,
  Member$inboundSchema,
  Member$Outbound,
  Member$outboundSchema,
} from "./member.js";

export type PagedMember = {
  /**
   * Current page number
   */
  currentPage: number;
  /**
   * Whether there is a next page
   */
  hasNext: boolean;
  /**
   * Whether there is a previous page
   */
  hasPrevious: boolean;
  items: Array<Member>;
  /**
   * Total number of items
   */
  totalCount: number;
  /**
   * Total number of pages
   */
  totalPages: number;
};

/** @internal */
export const PagedMember$inboundSchema: z.ZodType<
  PagedMember,
  z.ZodTypeDef,
  unknown
> = z.object({
  current_page: z.number().int(),
  has_next: z.boolean(),
  has_previous: z.boolean(),
  items: z.array(Member$inboundSchema),
  total_count: z.number().int(),
  total_pages: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "current_page": "currentPage",
    "has_next": "hasNext",
    "has_previous": "hasPrevious",
    "total_count": "totalCount",
    "total_pages": "totalPages",
  });
});

/** @internal */
export type PagedMember$Outbound = {
  current_page: number;
  has_next: boolean;
  has_previous: boolean;
  items: Array<Member$Outbound>;
  total_count: number;
  total_pages: number;
};

/** @internal */
export const PagedMember$outboundSchema: z.ZodType<
  PagedMember$Outbound,
  z.ZodTypeDef,
  PagedMember
> = z.object({
  currentPage: z.number().int(),
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  items: z.array(Member$outboundSchema),
  totalCount: z.number().int(),
  totalPages: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    currentPage: "current_page",
    hasNext: "has_next",
    hasPrevious: "has_previous",
    totalCount: "total_count",
    totalPages: "total_pages",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PagedMember$ {
  /** @deprecated use `PagedMember$inboundSchema` instead. */
  export const inboundSchema = PagedMember$inboundSchema;
  /** @deprecated use `PagedMember$outboundSchema` instead. */
  export const outboundSchema = PagedMember$outboundSchema;
  /** @deprecated use `PagedMember$Outbound` instead. */
  export type Outbound = PagedMember$Outbound;
}

export function pagedMemberToJSON(pagedMember: PagedMember): string {
  return JSON.stringify(PagedMember$outboundSchema.parse(pagedMember));
}

export function pagedMemberFromJSON(
  jsonString: string,
): SafeParseResult<PagedMember, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PagedMember$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PagedMember' from JSON`,
  );
}
