/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  IssueSchema,
  IssueSchema$inboundSchema,
  IssueSchema$Outbound,
  IssueSchema$outboundSchema,
} from "./issueschema.js";

export type PagedIssueSchema = {
  items: Array<IssueSchema>;
  count: number;
};

/** @internal */
export const PagedIssueSchema$inboundSchema: z.ZodType<
  PagedIssueSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(IssueSchema$inboundSchema),
  count: z.number().int(),
});

/** @internal */
export type PagedIssueSchema$Outbound = {
  items: Array<IssueSchema$Outbound>;
  count: number;
};

/** @internal */
export const PagedIssueSchema$outboundSchema: z.ZodType<
  PagedIssueSchema$Outbound,
  z.ZodTypeDef,
  PagedIssueSchema
> = z.object({
  items: z.array(IssueSchema$outboundSchema),
  count: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PagedIssueSchema$ {
  /** @deprecated use `PagedIssueSchema$inboundSchema` instead. */
  export const inboundSchema = PagedIssueSchema$inboundSchema;
  /** @deprecated use `PagedIssueSchema$outboundSchema` instead. */
  export const outboundSchema = PagedIssueSchema$outboundSchema;
  /** @deprecated use `PagedIssueSchema$Outbound` instead. */
  export type Outbound = PagedIssueSchema$Outbound;
}

export function pagedIssueSchemaToJSON(
  pagedIssueSchema: PagedIssueSchema,
): string {
  return JSON.stringify(
    PagedIssueSchema$outboundSchema.parse(pagedIssueSchema),
  );
}

export function pagedIssueSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PagedIssueSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PagedIssueSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PagedIssueSchema' from JSON`,
  );
}
