/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Committee,
  Committee$inboundSchema,
  Committee$Outbound,
  Committee$outboundSchema,
} from "./committee.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PagedCommittee = {
  /**
   * Current page number
   */
  currentPage: number;
  /**
   * Whether there is a next page
   */
  hasNext: boolean;
  /**
   * Whether there is a previous page
   */
  hasPrevious: boolean;
  items: Array<Committee>;
  /**
   * Total number of items
   */
  totalCount: number;
  /**
   * Total number of pages
   */
  totalPages: number;
};

/** @internal */
export const PagedCommittee$inboundSchema: z.ZodType<
  PagedCommittee,
  z.ZodTypeDef,
  unknown
> = z.object({
  current_page: z.number().int(),
  has_next: z.boolean(),
  has_previous: z.boolean(),
  items: z.array(Committee$inboundSchema),
  total_count: z.number().int(),
  total_pages: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "current_page": "currentPage",
    "has_next": "hasNext",
    "has_previous": "hasPrevious",
    "total_count": "totalCount",
    "total_pages": "totalPages",
  });
});

/** @internal */
export type PagedCommittee$Outbound = {
  current_page: number;
  has_next: boolean;
  has_previous: boolean;
  items: Array<Committee$Outbound>;
  total_count: number;
  total_pages: number;
};

/** @internal */
export const PagedCommittee$outboundSchema: z.ZodType<
  PagedCommittee$Outbound,
  z.ZodTypeDef,
  PagedCommittee
> = z.object({
  currentPage: z.number().int(),
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  items: z.array(Committee$outboundSchema),
  totalCount: z.number().int(),
  totalPages: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    currentPage: "current_page",
    hasNext: "has_next",
    hasPrevious: "has_previous",
    totalCount: "total_count",
    totalPages: "total_pages",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PagedCommittee$ {
  /** @deprecated use `PagedCommittee$inboundSchema` instead. */
  export const inboundSchema = PagedCommittee$inboundSchema;
  /** @deprecated use `PagedCommittee$outboundSchema` instead. */
  export const outboundSchema = PagedCommittee$outboundSchema;
  /** @deprecated use `PagedCommittee$Outbound` instead. */
  export type Outbound = PagedCommittee$Outbound;
}

export function pagedCommitteeToJSON(pagedCommittee: PagedCommittee): string {
  return JSON.stringify(PagedCommittee$outboundSchema.parse(pagedCommittee));
}

export function pagedCommitteeFromJSON(
  jsonString: string,
): SafeParseResult<PagedCommittee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PagedCommittee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PagedCommittee' from JSON`,
  );
}
