/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Milestone,
  Milestone$inboundSchema,
  Milestone$Outbound,
  Milestone$outboundSchema,
} from "./milestone.js";

export type PagedMilestone = {
  /**
   * Current page number
   */
  currentPage: number;
  /**
   * Whether there is a next page
   */
  hasNext: boolean;
  /**
   * Whether there is a previous page
   */
  hasPrevious: boolean;
  items: Array<Milestone>;
  /**
   * Total number of items
   */
  totalCount: number;
  /**
   * Total number of pages
   */
  totalPages: number;
};

/** @internal */
export const PagedMilestone$inboundSchema: z.ZodType<
  PagedMilestone,
  z.ZodTypeDef,
  unknown
> = z.object({
  current_page: z.number().int(),
  has_next: z.boolean(),
  has_previous: z.boolean(),
  items: z.array(Milestone$inboundSchema),
  total_count: z.number().int(),
  total_pages: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "current_page": "currentPage",
    "has_next": "hasNext",
    "has_previous": "hasPrevious",
    "total_count": "totalCount",
    "total_pages": "totalPages",
  });
});

/** @internal */
export type PagedMilestone$Outbound = {
  current_page: number;
  has_next: boolean;
  has_previous: boolean;
  items: Array<Milestone$Outbound>;
  total_count: number;
  total_pages: number;
};

/** @internal */
export const PagedMilestone$outboundSchema: z.ZodType<
  PagedMilestone$Outbound,
  z.ZodTypeDef,
  PagedMilestone
> = z.object({
  currentPage: z.number().int(),
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  items: z.array(Milestone$outboundSchema),
  totalCount: z.number().int(),
  totalPages: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    currentPage: "current_page",
    hasNext: "has_next",
    hasPrevious: "has_previous",
    totalCount: "total_count",
    totalPages: "total_pages",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PagedMilestone$ {
  /** @deprecated use `PagedMilestone$inboundSchema` instead. */
  export const inboundSchema = PagedMilestone$inboundSchema;
  /** @deprecated use `PagedMilestone$outboundSchema` instead. */
  export const outboundSchema = PagedMilestone$outboundSchema;
  /** @deprecated use `PagedMilestone$Outbound` instead. */
  export type Outbound = PagedMilestone$Outbound;
}

export function pagedMilestoneToJSON(pagedMilestone: PagedMilestone): string {
  return JSON.stringify(PagedMilestone$outboundSchema.parse(pagedMilestone));
}

export function pagedMilestoneFromJSON(
  jsonString: string,
): SafeParseResult<PagedMilestone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PagedMilestone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PagedMilestone' from JSON`,
  );
}
