/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MemberSchema,
  MemberSchema$inboundSchema,
  MemberSchema$Outbound,
  MemberSchema$outboundSchema,
} from "./memberschema.js";

export type PagedMemberSchema = {
  items: Array<MemberSchema>;
  count: number;
};

/** @internal */
export const PagedMemberSchema$inboundSchema: z.ZodType<
  PagedMemberSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(MemberSchema$inboundSchema),
  count: z.number().int(),
});

/** @internal */
export type PagedMemberSchema$Outbound = {
  items: Array<MemberSchema$Outbound>;
  count: number;
};

/** @internal */
export const PagedMemberSchema$outboundSchema: z.ZodType<
  PagedMemberSchema$Outbound,
  z.ZodTypeDef,
  PagedMemberSchema
> = z.object({
  items: z.array(MemberSchema$outboundSchema),
  count: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PagedMemberSchema$ {
  /** @deprecated use `PagedMemberSchema$inboundSchema` instead. */
  export const inboundSchema = PagedMemberSchema$inboundSchema;
  /** @deprecated use `PagedMemberSchema$outboundSchema` instead. */
  export const outboundSchema = PagedMemberSchema$outboundSchema;
  /** @deprecated use `PagedMemberSchema$Outbound` instead. */
  export type Outbound = PagedMemberSchema$Outbound;
}

export function pagedMemberSchemaToJSON(
  pagedMemberSchema: PagedMemberSchema,
): string {
  return JSON.stringify(
    PagedMemberSchema$outboundSchema.parse(pagedMemberSchema),
  );
}

export function pagedMemberSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PagedMemberSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PagedMemberSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PagedMemberSchema' from JSON`,
  );
}
