/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  EventSchema,
  EventSchema$inboundSchema,
  EventSchema$Outbound,
  EventSchema$outboundSchema,
} from "./eventschema.js";

export type PagedEventSchema = {
  items: Array<EventSchema>;
  count: number;
};

/** @internal */
export const PagedEventSchema$inboundSchema: z.ZodType<
  PagedEventSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(EventSchema$inboundSchema),
  count: z.number().int(),
});

/** @internal */
export type PagedEventSchema$Outbound = {
  items: Array<EventSchema$Outbound>;
  count: number;
};

/** @internal */
export const PagedEventSchema$outboundSchema: z.ZodType<
  PagedEventSchema$Outbound,
  z.ZodTypeDef,
  PagedEventSchema
> = z.object({
  items: z.array(EventSchema$outboundSchema),
  count: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PagedEventSchema$ {
  /** @deprecated use `PagedEventSchema$inboundSchema` instead. */
  export const inboundSchema = PagedEventSchema$inboundSchema;
  /** @deprecated use `PagedEventSchema$outboundSchema` instead. */
  export const outboundSchema = PagedEventSchema$outboundSchema;
  /** @deprecated use `PagedEventSchema$Outbound` instead. */
  export type Outbound = PagedEventSchema$Outbound;
}

export function pagedEventSchemaToJSON(
  pagedEventSchema: PagedEventSchema,
): string {
  return JSON.stringify(
    PagedEventSchema$outboundSchema.parse(pagedEventSchema),
  );
}

export function pagedEventSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PagedEventSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PagedEventSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PagedEventSchema' from JSON`,
  );
}
