/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Chapter, Chapter$inboundSchema } from "./chapter.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PagedChapter = {
  /**
   * Current page number
   */
  currentPage: number;
  /**
   * Whether there is a next page
   */
  hasNext: boolean;
  /**
   * Whether there is a previous page
   */
  hasPrevious: boolean;
  items: Array<Chapter>;
  /**
   * Total number of items
   */
  totalCount: number;
  /**
   * Total number of pages
   */
  totalPages: number;
};

/** @internal */
export const PagedChapter$inboundSchema: z.ZodType<
  PagedChapter,
  z.ZodTypeDef,
  unknown
> = z.object({
  current_page: z.number().int(),
  has_next: z.boolean(),
  has_previous: z.boolean(),
  items: z.array(Chapter$inboundSchema),
  total_count: z.number().int(),
  total_pages: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "current_page": "currentPage",
    "has_next": "hasNext",
    "has_previous": "hasPrevious",
    "total_count": "totalCount",
    "total_pages": "totalPages",
  });
});

export function pagedChapterFromJSON(
  jsonString: string,
): SafeParseResult<PagedChapter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PagedChapter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PagedChapter' from JSON`,
  );
}
