/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Enum for OWASP project levels.
 */
export const ProjectLevel = {
  Other: "other",
  Incubator: "incubator",
  Lab: "lab",
  Production: "production",
  Flagship: "flagship",
} as const;
/**
 * Enum for OWASP project levels.
 */
export type ProjectLevel = ClosedEnum<typeof ProjectLevel>;

/** @internal */
export const ProjectLevel$inboundSchema: z.ZodNativeEnum<typeof ProjectLevel> =
  z.nativeEnum(ProjectLevel);
/** @internal */
export const ProjectLevel$outboundSchema: z.ZodNativeEnum<typeof ProjectLevel> =
  ProjectLevel$inboundSchema;
