/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Leader, Leader$inboundSchema } from "./leader.js";
import { ProjectLevel, ProjectLevel$inboundSchema } from "./projectlevel.js";

/**
 * Detail schema for Project (used in single item endpoints).
 */
export type ProjectDetail = {
  createdAt: Date;
  key: string;
  /**
   * Enum for OWASP project levels.
   */
  level: ProjectLevel;
  name: string;
  updatedAt: Date;
  description: string;
  leaders: Array<Leader>;
};

/** @internal */
export const ProjectDetail$inboundSchema: z.ZodType<
  ProjectDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  key: z.string(),
  level: ProjectLevel$inboundSchema,
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  description: z.string(),
  leaders: z.array(Leader$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function projectDetailFromJSON(
  jsonString: string,
): SafeParseResult<ProjectDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProjectDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProjectDetail' from JSON`,
  );
}
