/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Enum for OWASP project levels.
 */
export const ProjectLevel = {
  Other: "other",
  Incubator: "incubator",
  Lab: "lab",
  Production: "production",
  Flagship: "flagship",
} as const;
/**
 * Enum for OWASP project levels.
 */
export type ProjectLevel = ClosedEnum<typeof ProjectLevel>;

/** @internal */
export const ProjectLevel$inboundSchema: z.ZodNativeEnum<typeof ProjectLevel> =
  z.nativeEnum(ProjectLevel);

/** @internal */
export const ProjectLevel$outboundSchema: z.ZodNativeEnum<typeof ProjectLevel> =
  ProjectLevel$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectLevel$ {
  /** @deprecated use `ProjectLevel$inboundSchema` instead. */
  export const inboundSchema = ProjectLevel$inboundSchema;
  /** @deprecated use `ProjectLevel$outboundSchema` instead. */
  export const outboundSchema = ProjectLevel$outboundSchema;
}
