/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Enum for OWASP project types.
 */
export const ProjectType = {
  Code: "code",
  Documentation: "documentation",
  Other: "other",
  Tool: "tool",
} as const;
/**
 * Enum for OWASP project types.
 */
export type ProjectType = ClosedEnum<typeof ProjectType>;

/** @internal */
export const ProjectType$inboundSchema: z.ZodNativeEnum<typeof ProjectType> = z
  .nativeEnum(ProjectType);
/** @internal */
export const ProjectType$outboundSchema: z.ZodNativeEnum<typeof ProjectType> =
  ProjectType$inboundSchema;
