/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Release (minimal fields for list display).
 */
export type Release = {
  createdAt: Date;
  name: string;
  publishedAt?: Date | null | undefined;
  tagName: string;
};

/** @internal */
export const Release$inboundSchema: z.ZodType<Release, z.ZodTypeDef, unknown> =
  z.object({
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    name: z.string(),
    published_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    tag_name: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "published_at": "publishedAt",
      "tag_name": "tagName",
    });
  });

export function releaseFromJSON(
  jsonString: string,
): SafeParseResult<Release, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Release$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Release' from JSON`,
  );
}
