/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Release (used in single item endpoints).
 */
export type ReleaseDetail = {
  createdAt: Date;
  name: string;
  publishedAt?: Date | null | undefined;
  tagName: string;
  description: string;
};

/** @internal */
export const ReleaseDetail$inboundSchema: z.ZodType<
  ReleaseDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  name: z.string(),
  published_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  tag_name: z.string(),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "published_at": "publishedAt",
    "tag_name": "tagName",
  });
});

export function releaseDetailFromJSON(
  jsonString: string,
): SafeParseResult<ReleaseDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReleaseDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReleaseDetail' from JSON`,
  );
}
