/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Release (minimal fields for list display).
 */
export type Release = {
  createdAt: Date;
  name: string;
  publishedAt?: Date | null | undefined;
  tagName: string;
};

/** @internal */
export const Release$inboundSchema: z.ZodType<Release, z.ZodTypeDef, unknown> =
  z.object({
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    name: z.string(),
    published_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    tag_name: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "published_at": "publishedAt",
      "tag_name": "tagName",
    });
  });

/** @internal */
export type Release$Outbound = {
  created_at: string;
  name: string;
  published_at?: string | null | undefined;
  tag_name: string;
};

/** @internal */
export const Release$outboundSchema: z.ZodType<
  Release$Outbound,
  z.ZodTypeDef,
  Release
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  name: z.string(),
  publishedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  tagName: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    publishedAt: "published_at",
    tagName: "tag_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Release$ {
  /** @deprecated use `Release$inboundSchema` instead. */
  export const inboundSchema = Release$inboundSchema;
  /** @deprecated use `Release$outboundSchema` instead. */
  export const outboundSchema = Release$outboundSchema;
  /** @deprecated use `Release$Outbound` instead. */
  export type Outbound = Release$Outbound;
}

export function releaseToJSON(release: Release): string {
  return JSON.stringify(Release$outboundSchema.parse(release));
}

export function releaseFromJSON(
  jsonString: string,
): SafeParseResult<Release, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Release$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Release' from JSON`,
  );
}
