/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Repository (used in single item endpoints).
 */
export type RepositoryDetail = {
  createdAt: Date;
  name: string;
  updatedAt: Date;
  commitsCount: number;
  contributorsCount: number;
  description?: string | null | undefined;
  forksCount: number;
  openIssuesCount: number;
  starsCount: number;
};

/** @internal */
export const RepositoryDetail$inboundSchema: z.ZodType<
  RepositoryDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  commits_count: z.number().int(),
  contributors_count: z.number().int(),
  description: z.nullable(z.string()).optional(),
  forks_count: z.number().int(),
  open_issues_count: z.number().int(),
  stars_count: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "commits_count": "commitsCount",
    "contributors_count": "contributorsCount",
    "forks_count": "forksCount",
    "open_issues_count": "openIssuesCount",
    "stars_count": "starsCount",
  });
});

export function repositoryDetailFromJSON(
  jsonString: string,
): SafeParseResult<RepositoryDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RepositoryDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RepositoryDetail' from JSON`,
  );
}
