/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Repository (minimal fields for list display).
 */
export type Repository = {
  createdAt: Date;
  name: string;
  updatedAt: Date;
};

/** @internal */
export const Repository$inboundSchema: z.ZodType<
  Repository,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type Repository$Outbound = {
  created_at: string;
  name: string;
  updated_at: string;
};

/** @internal */
export const Repository$outboundSchema: z.ZodType<
  Repository$Outbound,
  z.ZodTypeDef,
  Repository
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Repository$ {
  /** @deprecated use `Repository$inboundSchema` instead. */
  export const inboundSchema = Repository$inboundSchema;
  /** @deprecated use `Repository$outboundSchema` instead. */
  export const outboundSchema = Repository$outboundSchema;
  /** @deprecated use `Repository$Outbound` instead. */
  export type Outbound = Repository$Outbound;
}

export function repositoryToJSON(repository: Repository): string {
  return JSON.stringify(Repository$outboundSchema.parse(repository));
}

export function repositoryFromJSON(
  jsonString: string,
): SafeParseResult<Repository, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Repository$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Repository' from JSON`,
  );
}
