/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Repository (minimal fields for list display).
 */
export type Repository = {
  createdAt: Date;
  name: string;
  updatedAt: Date;
};

/** @internal */
export const Repository$inboundSchema: z.ZodType<
  Repository,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function repositoryFromJSON(
  jsonString: string,
): SafeParseResult<Repository, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Repository$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Repository' from JSON`,
  );
}
