/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Repository.
 */
export type RepositorySchema = {
  createdAt: Date;
  description: string;
  name: string;
  updatedAt: Date;
};

/** @internal */
export const RepositorySchema$inboundSchema: z.ZodType<
  RepositorySchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  description: z.string(),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type RepositorySchema$Outbound = {
  created_at: string;
  description: string;
  name: string;
  updated_at: string;
};

/** @internal */
export const RepositorySchema$outboundSchema: z.ZodType<
  RepositorySchema$Outbound,
  z.ZodTypeDef,
  RepositorySchema
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  description: z.string(),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RepositorySchema$ {
  /** @deprecated use `RepositorySchema$inboundSchema` instead. */
  export const inboundSchema = RepositorySchema$inboundSchema;
  /** @deprecated use `RepositorySchema$outboundSchema` instead. */
  export const outboundSchema = RepositorySchema$outboundSchema;
  /** @deprecated use `RepositorySchema$Outbound` instead. */
  export type Outbound = RepositorySchema$Outbound;
}

export function repositorySchemaToJSON(
  repositorySchema: RepositorySchema,
): string {
  return JSON.stringify(
    RepositorySchema$outboundSchema.parse(repositorySchema),
  );
}

export function repositorySchemaFromJSON(
  jsonString: string,
): SafeParseResult<RepositorySchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RepositorySchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RepositorySchema' from JSON`,
  );
}
