/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Repository (used in single item endpoints).
 */
export type RepositoryDetail = {
  createdAt: Date;
  name: string;
  updatedAt: Date;
  description?: string | null | undefined;
};

/** @internal */
export const RepositoryDetail$inboundSchema: z.ZodType<
  RepositoryDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  name: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type RepositoryDetail$Outbound = {
  created_at: string;
  name: string;
  updated_at: string;
  description?: string | null | undefined;
};

/** @internal */
export const RepositoryDetail$outboundSchema: z.ZodType<
  RepositoryDetail$Outbound,
  z.ZodTypeDef,
  RepositoryDetail
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  name: z.string(),
  updatedAt: z.date().transform(v => v.toISOString()),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RepositoryDetail$ {
  /** @deprecated use `RepositoryDetail$inboundSchema` instead. */
  export const inboundSchema = RepositoryDetail$inboundSchema;
  /** @deprecated use `RepositoryDetail$outboundSchema` instead. */
  export const outboundSchema = RepositoryDetail$outboundSchema;
  /** @deprecated use `RepositoryDetail$Outbound` instead. */
  export type Outbound = RepositoryDetail$Outbound;
}

export function repositoryDetailToJSON(
  repositoryDetail: RepositoryDetail,
): string {
  return JSON.stringify(
    RepositoryDetail$outboundSchema.parse(repositoryDetail),
  );
}

export function repositoryDetailFromJSON(
  jsonString: string,
): SafeParseResult<RepositoryDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RepositoryDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RepositoryDetail' from JSON`,
  );
}
