/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { State, State$inboundSchema } from "./state.js";

/**
 * Schema for Snapshot Issue (used in list endpoints).
 */
export type SnapshotIssue = {
  createdAt: Date;
  state: State;
  title: string;
  updatedAt: Date;
  url: string;
  organizationLogin: string | null;
  repositoryName: string | null;
};

/** @internal */
export const SnapshotIssue$inboundSchema: z.ZodType<
  SnapshotIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  state: State$inboundSchema,
  title: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  url: z.string(),
  organization_login: z.nullable(z.string()),
  repository_name: z.nullable(z.string()),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "organization_login": "organizationLogin",
    "repository_name": "repositoryName",
  });
});

export function snapshotIssueFromJSON(
  jsonString: string,
): SafeParseResult<SnapshotIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SnapshotIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SnapshotIssue' from JSON`,
  );
}
