/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Snapshot Release (used in list endpoints).
 */
export type SnapshotRelease = {
  createdAt: Date;
  name: string;
  publishedAt?: Date | null | undefined;
  tagName: string;
  organizationLogin: string | null;
  repositoryName: string | null;
};

/** @internal */
export const SnapshotRelease$inboundSchema: z.ZodType<
  SnapshotRelease,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  name: z.string(),
  published_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  tag_name: z.string(),
  organization_login: z.nullable(z.string()),
  repository_name: z.nullable(z.string()),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "published_at": "publishedAt",
    "tag_name": "tagName",
    "organization_login": "organizationLogin",
    "repository_name": "repositoryName",
  });
});

export function snapshotReleaseFromJSON(
  jsonString: string,
): SafeParseResult<SnapshotRelease, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SnapshotRelease$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SnapshotRelease' from JSON`,
  );
}
