/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Detail schema for Snapshot (used in single item endpoints).
 */
export type SnapshotDetail = {
  createdAt: Date;
  endAt: Date;
  key: string;
  startAt: Date;
  title: string;
  updatedAt: Date;
  newChaptersCount: number;
  newIssuesCount: number;
  newProjectsCount: number;
  newReleasesCount: number;
  newUsersCount: number;
};

/** @internal */
export const SnapshotDetail$inboundSchema: z.ZodType<
  SnapshotDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  end_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  key: z.string(),
  start_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  title: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  new_chapters_count: z.number().int(),
  new_issues_count: z.number().int(),
  new_projects_count: z.number().int(),
  new_releases_count: z.number().int(),
  new_users_count: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "end_at": "endAt",
    "start_at": "startAt",
    "updated_at": "updatedAt",
    "new_chapters_count": "newChaptersCount",
    "new_issues_count": "newIssuesCount",
    "new_projects_count": "newProjectsCount",
    "new_releases_count": "newReleasesCount",
    "new_users_count": "newUsersCount",
  });
});

export function snapshotDetailFromJSON(
  jsonString: string,
): SafeParseResult<SnapshotDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SnapshotDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SnapshotDetail' from JSON`,
  );
}
