/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Snapshot (minimal fields for list display).
 */
export type Snapshot = {
  createdAt: Date;
  endAt: Date;
  key: string;
  startAt: Date;
  title: string;
  updatedAt: Date;
};

/** @internal */
export const Snapshot$inboundSchema: z.ZodType<
  Snapshot,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  end_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  key: z.string(),
  start_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  title: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "end_at": "endAt",
    "start_at": "startAt",
    "updated_at": "updatedAt",
  });
});

export function snapshotFromJSON(
  jsonString: string,
): SafeParseResult<Snapshot, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Snapshot$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Snapshot' from JSON`,
  );
}
