/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Sponsor.
 */
export type SponsorSchema = {
  description: string;
  imageUrl: string;
  isMember: boolean;
  jobUrl: string;
  key: string;
  memberType: string;
  name: string;
  sponsorType: string;
  url: string;
};

/** @internal */
export const SponsorSchema$inboundSchema: z.ZodType<
  SponsorSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string(),
  image_url: z.string(),
  is_member: z.boolean(),
  job_url: z.string(),
  key: z.string(),
  member_type: z.string(),
  name: z.string(),
  sponsor_type: z.string(),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "image_url": "imageUrl",
    "is_member": "isMember",
    "job_url": "jobUrl",
    "member_type": "memberType",
    "sponsor_type": "sponsorType",
  });
});

/** @internal */
export type SponsorSchema$Outbound = {
  description: string;
  image_url: string;
  is_member: boolean;
  job_url: string;
  key: string;
  member_type: string;
  name: string;
  sponsor_type: string;
  url: string;
};

/** @internal */
export const SponsorSchema$outboundSchema: z.ZodType<
  SponsorSchema$Outbound,
  z.ZodTypeDef,
  SponsorSchema
> = z.object({
  description: z.string(),
  imageUrl: z.string(),
  isMember: z.boolean(),
  jobUrl: z.string(),
  key: z.string(),
  memberType: z.string(),
  name: z.string(),
  sponsorType: z.string(),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
    isMember: "is_member",
    jobUrl: "job_url",
    memberType: "member_type",
    sponsorType: "sponsor_type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SponsorSchema$ {
  /** @deprecated use `SponsorSchema$inboundSchema` instead. */
  export const inboundSchema = SponsorSchema$inboundSchema;
  /** @deprecated use `SponsorSchema$outboundSchema` instead. */
  export const outboundSchema = SponsorSchema$outboundSchema;
  /** @deprecated use `SponsorSchema$Outbound` instead. */
  export type Outbound = SponsorSchema$Outbound;
}

export function sponsorSchemaToJSON(sponsorSchema: SponsorSchema): string {
  return JSON.stringify(SponsorSchema$outboundSchema.parse(sponsorSchema));
}

export function sponsorSchemaFromJSON(
  jsonString: string,
): SafeParseResult<SponsorSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SponsorSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SponsorSchema' from JSON`,
  );
}
