/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Schema for Sponsor (minimal fields for list display).
 */
export type Sponsor = {
  imageUrl: string;
  key: string;
  name: string;
  sponsorType: string;
  url: string;
};

/** @internal */
export const Sponsor$inboundSchema: z.ZodType<Sponsor, z.ZodTypeDef, unknown> =
  z.object({
    image_url: z.string(),
    key: z.string(),
    name: z.string(),
    sponsor_type: z.string(),
    url: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
      "sponsor_type": "sponsorType",
    });
  });

export function sponsorFromJSON(
  jsonString: string,
): SafeParseResult<Sponsor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sponsor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sponsor' from JSON`,
  );
}
