name: Publish SDK

on:
  push:
    branches:
      - main
    paths:
      - .speakeasy/gen.lock

permissions:
  checks: write
  contents: write
  id-token: write
  pull-requests: write
  statuses: write

jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      target: nest-sdk-typescript
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
